// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ActivityItem struct {
	Type       string    `json:"type"`
	ThreadID   string    `json:"threadId"`
	ThreadName string    `json:"threadName"`
	Summary    string    `json:"summary"`
	Timestamp  time.Time `json:"timestamp"`
}

type AgentState struct {
	ThreadID      string      `json:"threadId"`
	Status        AgentStatus `json:"status"`
	Mode          AgentMode   `json:"mode"`
	RoundCount    int         `json:"roundCount"`
	StartedAt     *time.Time  `json:"startedAt,omitempty"`
	DurationLimit *string     `json:"durationLimit,omitempty"`
	ElapsedTime   *string     `json:"elapsedTime,omitempty"`
	PlanContent   *string     `json:"planContent,omitempty"`
	// Retry status of the underlying provider call. Null when not retrying.
	Retry *RetryStatus `json:"retry,omitempty"`
}

// Attachment metadata on a message. Files live in the thread's sandbox
// workspace under `_attachments/{id}/{filename}`; `path` is the
// sandbox-relative location the agent resolves via FileRead. Download
// via GET /api/attachments/{threadId}/{id}/{filename}.
type AttachmentBlock struct {
	ID        string `json:"id"`
	Filename  string `json:"filename"`
	MimeType  string `json:"mimeType"`
	SizeBytes int    `json:"sizeBytes"`
	Path      string `json:"path"`
}

// AttachmentInput is the shape the client sends after a successful
// POST /api/attachments/{threadId} — echoing what that endpoint
// returned. The server reconstructs AttachmentContent blocks from
// these and stamps them into the message at send time.
type AttachmentInput struct {
	ID          string  `json:"id"`
	Filename    string  `json:"filename"`
	MimeType    string  `json:"mimeType"`
	SizeBytes   int     `json:"sizeBytes"`
	Path        string  `json:"path"`
	InlinedText *string `json:"inlinedText,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

// Transient-failure retry progress for the current LLM request.
// Surfaced to the UI so the user sees "retrying 2/10, next attempt in
// 8s" instead of a silent pause.
type RetryStatus struct {
	Attempt     int `json:"attempt"`
	MaxAttempts int `json:"maxAttempts"`
	// Last error message that triggered the retry (null on success).
	Error *string `json:"error,omitempty"`
	// Milliseconds until the next attempt. 0 when this is the final event.
	NextDelayMs int `json:"nextDelayMs"`
	// True when no more attempts will be made (success or exhaustion).
	Final bool `json:"final"`
}

type SearchResult struct {
	MessageID  string  `json:"messageId"`
	ThreadID   string  `json:"threadId"`
	ThreadName string  `json:"threadName"`
	Snippet    string  `json:"snippet"`
	Score      float64 `json:"score"`
}

type Settings struct {
	Providers   string `json:"providers"`
	Permissions string `json:"permissions"`
	McpServers  string `json:"mcpServers"`
	Hooks       string `json:"hooks"`
	Preferences string `json:"preferences"`
	// Engine config as JSON: { edgeThreshold, scoreFloor, weightCE, weightTemp, radiusSize, rerankTopK }.
	// Live-tunable — the RRC engine re-projects stored edges under the new config
	// at walk time, so saving here changes Selection behavior on the next turn
	// without a restart. Raw reranker scores are preserved; only the fused
	// projection shifts.
	Engine string `json:"engine"`
}

type SettingsInput struct {
	Providers   *string `json:"providers,omitempty"`
	Permissions *string `json:"permissions,omitempty"`
	McpServers  *string `json:"mcpServers,omitempty"`
	Hooks       *string `json:"hooks,omitempty"`
	Preferences *string `json:"preferences,omitempty"`
	Engine      *string `json:"engine,omitempty"`
}

type SkillInfo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type StreamEvent struct {
	MessageID string  `json:"messageId"`
	Delta     *string `json:"delta,omitempty"`
	Thinking  *string `json:"thinking,omitempty"`
	Done      bool    `json:"done"`
	Error     *string `json:"error,omitempty"`
}

type SubagentProgress struct {
	ThreadID     string `json:"threadId"`
	ForkThreadID string `json:"forkThreadId"`
	Task         string `json:"task"`
	Status       string `json:"status"`
	RoundCount   int    `json:"roundCount"`
}

type Subscription struct {
}

type ThreadStateEvent struct {
	ThreadID string      `json:"threadId"`
	Status   AgentStatus `json:"status"`
	Mode     AgentMode   `json:"mode"`
	Warmth   int         `json:"warmth"`
	Name     string      `json:"name"`
}

type ToolCallBlock struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

type ToolExecution struct {
	ThreadID  string  `json:"threadId"`
	CallID    string  `json:"callId"`
	ToolName  string  `json:"toolName"`
	Arguments string  `json:"arguments"`
	Status    string  `json:"status"`
	Result    *string `json:"result,omitempty"`
	IsError   *bool   `json:"isError,omitempty"`
}

type ToolResultBlock struct {
	ToolCallID string `json:"toolCallId"`
	Content    string `json:"content"`
}

type ViewState struct {
	ThreadID               string   `json:"threadId"`
	ScrollPosition         float64  `json:"scrollPosition"`
	ExpandedMessageIds     []string `json:"expandedMessageIds"`
	InputDraft             string   `json:"inputDraft"`
	CitationExpansionState string   `json:"citationExpansionState"`
}

type ViewStateInput struct {
	ScrollPosition         float64  `json:"scrollPosition"`
	ExpandedMessageIds     []string `json:"expandedMessageIds"`
	InputDraft             string   `json:"inputDraft"`
	CitationExpansionState string   `json:"citationExpansionState"`
}

type AgentMode string

const (
	AgentModeNormal     AgentMode = "NORMAL"
	AgentModeAutonomous AgentMode = "AUTONOMOUS"
	AgentModePlan       AgentMode = "PLAN"
)

var AllAgentMode = []AgentMode{
	AgentModeNormal,
	AgentModeAutonomous,
	AgentModePlan,
}

func (e AgentMode) IsValid() bool {
	switch e {
	case AgentModeNormal, AgentModeAutonomous, AgentModePlan:
		return true
	}
	return false
}

func (e AgentMode) String() string {
	return string(e)
}

func (e *AgentMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentMode", str)
	}
	return nil
}

func (e AgentMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentStatus string

const (
	AgentStatusIdle    AgentStatus = "IDLE"
	AgentStatusRunning AgentStatus = "RUNNING"
	AgentStatusPaused  AgentStatus = "PAUSED"
)

var AllAgentStatus = []AgentStatus{
	AgentStatusIdle,
	AgentStatusRunning,
	AgentStatusPaused,
}

func (e AgentStatus) IsValid() bool {
	switch e {
	case AgentStatusIdle, AgentStatusRunning, AgentStatusPaused:
		return true
	}
	return false
}

func (e AgentStatus) String() string {
	return string(e)
}

func (e *AgentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentStatus", str)
	}
	return nil
}

func (e AgentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ExecutionMode string

const (
	ExecutionModeManual     ExecutionMode = "MANUAL"
	ExecutionModeAutonomous ExecutionMode = "AUTONOMOUS"
)

var AllExecutionMode = []ExecutionMode{
	ExecutionModeManual,
	ExecutionModeAutonomous,
}

func (e ExecutionMode) IsValid() bool {
	switch e {
	case ExecutionModeManual, ExecutionModeAutonomous:
		return true
	}
	return false
}

func (e ExecutionMode) String() string {
	return string(e)
}

func (e *ExecutionMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExecutionMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExecutionMode", str)
	}
	return nil
}

func (e ExecutionMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExecutionMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExecutionMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SelectionScope string

const (
	SelectionScopeThread     SelectionScope = "THREAD"
	SelectionScopeAllThreads SelectionScope = "ALL_THREADS"
)

var AllSelectionScope = []SelectionScope{
	SelectionScopeThread,
	SelectionScopeAllThreads,
}

func (e SelectionScope) IsValid() bool {
	switch e {
	case SelectionScopeThread, SelectionScopeAllThreads:
		return true
	}
	return false
}

func (e SelectionScope) String() string {
	return string(e)
}

func (e *SelectionScope) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SelectionScope(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SelectionScope", str)
	}
	return nil
}

func (e SelectionScope) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SelectionScope) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SelectionScope) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
