package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/elijahmontenegro/grudge/adoc"
	threadv1 "github.com/elijahmontenegro/grudge/proto/gen/go/grudge/thread/v1"
	"github.com/elijahmontenegro/grudge/proto/pbtext"
	"github.com/elijahmontenegro/grudge/service/storage"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// Role is the resolver for the role field.
func (r *messageResolver) Role(ctx context.Context, obj *threadv1.Message) (string, error) {
	return protoRoleToDisplay(obj.Role), nil
}

// Content is the resolver for the content field.
func (r *messageResolver) Content(ctx context.Context, obj *threadv1.Message) (string, error) {
	return protoContentToDisplay(obj.Content), nil
}

// Thinking is the resolver for the thinking field.
func (r *messageResolver) Thinking(ctx context.Context, obj *threadv1.Message) (*string, error) {
	thinking := protoThinkingContent(obj.Content)
	if thinking == "" {
		return nil, nil
	}
	return &thinking, nil
}

// ToolCalls is the resolver for the toolCalls field.
func (r *messageResolver) ToolCalls(ctx context.Context, obj *threadv1.Message) ([]*ToolCallBlock, error) {
	calls := protoToolCalls(obj.Content)
	result := make([]*ToolCallBlock, len(calls))
	for i, tc := range calls {
		result[i] = &ToolCallBlock{ID: tc.Id, Name: tc.Name, Arguments: tc.Arguments}
	}
	return result, nil
}

// ToolResults is the resolver for the toolResults field.
func (r *messageResolver) ToolResults(ctx context.Context, obj *threadv1.Message) ([]*ToolResultBlock, error) {
	results := protoToolResults(obj.Content)
	out := make([]*ToolResultBlock, len(results))
	for i, tr := range results {
		out[i] = &ToolResultBlock{ToolCallID: tr.ToolCallId, Content: tr.Content}
	}
	return out, nil
}

// Attachments is the resolver for the attachments field. Walks the
// message's content blocks and surfaces any AttachmentContent as
// metadata-only blocks (the actual file bytes stay in the workspace;
// GraphQL returns references, clients fetch via the HTTP endpoint).
func (r *messageResolver) Attachments(ctx context.Context, obj *threadv1.Message) ([]*AttachmentBlock, error) {
	var out []*AttachmentBlock
	for _, b := range obj.Content {
		if a := b.GetAttachment(); a != nil {
			out = append(out, &AttachmentBlock{
				ID:        a.Id,
				Filename:  a.Filename,
				MimeType:  a.MimeType,
				SizeBytes: int(a.SizeBytes),
				Path:      a.Path,
			})
		}
	}
	return out, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *messageResolver) CreatedAt(ctx context.Context, obj *threadv1.Message) (*time.Time, error) {
	if obj.CreatedAt != nil {
		t := obj.CreatedAt.AsTime()
		return &t, nil
	}
	return nil, nil
}

// CitedByCount is the resolver for the citedByCount field.
func (r *messageResolver) CitedByCount(ctx context.Context, obj *threadv1.Message) (int, error) {
	return r.selections.CitationCount(obj.Id), nil
}

// EditMessage is the resolver for the editMessage field.
func (r *mutationResolver) EditMessage(ctx context.Context, threadID string, messagePosition int, newContent string) (*threadv1.Thread, error) {
	parentThread, err := r.db.GetThread(threadID)
	if err != nil {
		return nil, err
	}

	branchPos := int64(messagePosition)
	newThread := &threadv1.Thread{
		Id:                  fmt.Sprintf("thread-%d", time.Now().UnixNano()),
		Name:                parentThread.Name + " (branch)",
		WorkingDirs:         parentThread.WorkingDirs,
		Sandboxed:           parentThread.Sandboxed,
		CreatedAt:           timestamppb.Now(),
		ParentThreadId:      &threadID,
		BranchPointPosition: &branchPos,
	}
	if err := r.db.CreateThread(newThread); err != nil {
		return nil, err
	}

	// No Engine.Fork is needed: the global engine has the parent's edges and
	// query scores. The branch corpus references the parent's messages through
	// the branch point, and later Selection Queries can retrieve from that
	// inherited corpus.

	// Insert the edited message at the branch point
	msg := &threadv1.Message{
		Id:       fmt.Sprintf("msg-%s-0", newThread.Id),
		Role:     threadv1.Role_ROLE_USER,
		Content:  pbtext.BlocksFromText(newContent),
		Position: int64(messagePosition),
		ThreadId: newThread.Id,
	}
	if err := r.storeMessage(msg, newContent); err != nil {
		return nil, err
	}

	return newThread, nil
}

// CompileAdoc is the resolver for the compileAdoc field.
func (r *mutationResolver) CompileAdoc(ctx context.Context, path string) (string, error) {
	return adoc.Compile(path)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, threadID string, content string, scope *SelectionScope, attachments []*AttachmentInput) (*threadv1.Message, error) {
	// Auto-name thread from first user message
	corpus, err := r.db.ThreadCorpus(threadID)
	if err != nil {
		return nil, fmt.Errorf("load corpus: %w", err)
	}
	if len(corpus) == 0 && content != "" {
		if err := r.db.UpdateThreadName(threadID, storage.TruncateThreadName(content)); err != nil {
			return nil, fmt.Errorf("update thread name: %w", err)
		}
	}

	runner, err := r.getOrCreateRunner(threadID)
	if err != nil {
		return nil, fmt.Errorf("get runner: %w", err)
	}
	// Default scope is all-threads. The whole point of RRC is that
	// the user's prior conversations (any thread) can be pulled in when
	// relevant. Thread-only is the opt-out, not the default — the old
	// default made the agent look amnesiac ("I don't retain info across
	// chats") because it literally had no cross-thread context to pull.
	pbScope := threadv1.SelectionScope_SELECTION_SCOPE_ALL_THREADS
	if scope != nil && *scope == SelectionScopeThread {
		pbScope = threadv1.SelectionScope_SELECTION_SCOPE_THREAD
	}

	// Defer a publish of Status=Idle so the UI doesn't get stuck showing
	// "running" after the turn ends. ExitPlan's AgentState("normal")
	// callback flips Status=Running mid-turn; without this defer, that
	// state would persist until the user takes an explicit action like
	// stop or approve. Read current mode from DB so we don't clobber it.
	defer func() {
		st, err := r.db.GetAgentState(threadID)
		if err != nil {
			return
		}
		gqlMode := AgentModeNormal
		switch st.Mode {
		case storage.AgentModePlan:
			gqlMode = AgentModePlan
		case storage.AgentModeAutonomous:
			gqlMode = AgentModeAutonomous
		}
		// Don't clobber autonomous-in-progress — that loop publishes its
		// own Idle on exit via defer in StartAutonomous.
		if st.Mode == storage.AgentModeAutonomous && st.Status == storage.AgentStatusRunning {
			return
		}
		var planPtr *string
		if pc := r.plans.Get(threadID); pc != "" {
			planPtr = &pc
		}
		// Narrow UPDATE (round 93 helper) so we don't wipe StartedAt /
		// DurationLimit that an autonomous run may have set. Mode is
		// already whatever it was — SetAgentStatus leaves it alone.
		if err := r.db.SetAgentStatus(threadID, storage.AgentStatusIdle); err == nil {
			r.publishAgentState(threadID, &AgentState{
				ThreadID: threadID, Status: AgentStatusIdle, Mode: gqlMode,
				PlanContent: planPtr,
			})
		}
	}()

	// Filenames / sizes / paths are server-generated during upload
	// and echoed back, so no re-validation is needed at this boundary
	// (the files already exist on disk in the workspace).
	attachBlocks := attachmentInputsToBlocks(attachments)

	resp, err := runner.SendMessage(ctx, content, pbScope, attachBlocks...)
	if err != nil {
		return nil, fmt.Errorf("send message: %w", err)
	}
	return resp, nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, threadID string, limit *int, offset *int) ([]*threadv1.Message, error) {
	lim, off := 0, 0
	if limit != nil {
		lim = *limit
	}
	if offset != nil {
		off = *offset
	}
	msgs, err := r.db.ListMessages(threadID, lim, off)
	if err != nil {
		return nil, err
	}
	return msgs, nil
}

// MessageStream is the resolver for the messageStream field.
func (r *subscriptionResolver) MessageStream(ctx context.Context, threadID string) (<-chan *StreamEvent, error) {
	ch := r.streams.Subscribe(threadID)
	unsubscribeOnDone(ctx, func() { r.streams.Unsubscribe(threadID, ch) })
	return ch, nil
}

// Message returns MessageResolver implementation.
func (r *Resolver) Message() MessageResolver { return &messageResolver{r} }

type messageResolver struct{ *Resolver }
