package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	rrcv1 "github.com/elijahmontenegro/grudge/proto/gen/go/grudge/rrc/v1"
	threadv1 "github.com/elijahmontenegro/grudge/proto/gen/go/grudge/thread/v1"
	"github.com/elijahmontenegro/grudge/proto/pbtext"
)

// Score is the resolver for the score field.
func (r *edgeResolver) Score(ctx context.Context, obj *rrcv1.Edge) (float64, error) {
	return float64(obj.Score), nil
}

// Source is the resolver for the source field.
func (r *edgeResolver) Source(ctx context.Context, obj *rrcv1.Edge) (string, error) {
	return obj.Source.String(), nil
}

// CrossEncoderScore is the resolver for the crossEncoderScore field.
func (r *edgeResolver) CrossEncoderScore(ctx context.Context, obj *rrcv1.Edge) (float64, error) {
	return float64(obj.CrossEncoderScore), nil
}

// Reason is the resolver for the reason field.
func (r *excludedMessageResolver) Reason(ctx context.Context, obj *rrcv1.ExcludedMessage) (string, error) {
	return obj.Reason.String(), nil
}

// Score is the resolver for the score field.
func (r *excludedMessageResolver) Score(ctx context.Context, obj *rrcv1.ExcludedMessage) (float64, error) {
	return float64(obj.Score), nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, limit *int) ([]*SearchResult, error) {
	if r.substrate.Searcher() == nil {
		return nil, fmt.Errorf("search unavailable: embedder not configured")
	}
	lim := 10
	if limit != nil {
		lim = *limit
	}
	results, err := r.substrate.Searcher().Search(ctx, query, lim)
	if err != nil {
		return nil, err
	}
	gqlResults := make([]*SearchResult, len(results))
	for i, res := range results {
		msg, err := r.db.GetMessage(res.MessageID)
		if err != nil {
			continue
		}
		thread, _ := r.db.GetThread(msg.ThreadId)
		threadName := ""
		if thread != nil {
			threadName = thread.Name
		}
		gqlResults[i] = &SearchResult{
			MessageID:  res.MessageID,
			ThreadID:   msg.ThreadId,
			ThreadName: threadName,
			Snippet:    pbtext.TextFromBlocks(msg.Content),
			Score:      res.Score,
		}
	}
	return gqlResults, nil
}

// SelectionForMessage returns the SelectionResult that drove the turn
// which produced the given target message. Pure DB lookup — this is
// the primary path for auditing any historical turn, live or long past.
func (r *queryResolver) SelectionForMessage(ctx context.Context, messageID string) (*rrcv1.SelectionResult, error) {
	return r.db.GetSelectionForMessage(messageID)
}

// EffectiveScore is the resolver for the effectiveScore field.
func (r *selectedMessageResolver) EffectiveScore(ctx context.Context, obj *rrcv1.SelectedMessage) (float64, error) {
	return float64(obj.EffectiveScore), nil
}

// CrossEncoderScore is the resolver for the crossEncoderScore field.
func (r *selectedMessageResolver) CrossEncoderScore(ctx context.Context, obj *rrcv1.SelectedMessage) (float64, error) {
	if len(obj.ViaEdges) > 0 {
		return float64(obj.ViaEdges[0].CrossEncoderScore), nil
	}
	return 0, nil
}

// Scope is the resolver for the scope field.
func (r *selectionResultResolver) Scope(ctx context.Context, obj *rrcv1.SelectionResult) (SelectionScope, error) {
	if obj.Scope == threadv1.SelectionScope_SELECTION_SCOPE_ALL_THREADS {
		return SelectionScopeAllThreads, nil
	}
	return SelectionScopeThread, nil
}

// Edge returns EdgeResolver implementation.
func (r *Resolver) Edge() EdgeResolver { return &edgeResolver{r} }

// ExcludedMessage returns ExcludedMessageResolver implementation.
func (r *Resolver) ExcludedMessage() ExcludedMessageResolver { return &excludedMessageResolver{r} }

// SelectedMessage returns SelectedMessageResolver implementation.
func (r *Resolver) SelectedMessage() SelectedMessageResolver { return &selectedMessageResolver{r} }

// SelectionResult returns SelectionResultResolver implementation.
func (r *Resolver) SelectionResult() SelectionResultResolver { return &selectionResultResolver{r} }

type edgeResolver struct{ *Resolver }
type excludedMessageResolver struct{ *Resolver }
type selectedMessageResolver struct{ *Resolver }
type selectionResultResolver struct{ *Resolver }
