package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"fmt"
	"log"

	"github.com/emontenegr/spidey/service/config"
)

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input SettingsInput) (*Settings, error) {
	s := &r.cfg.Settings
	if input.Providers != nil {
		// Replace semantics, not merge. `json.Unmarshal` into an
		// existing map preserves keys the new payload omits; that
		// meant removing a provider in the UI never actually removed
		// it from disk. Zero the map first so the input is the
		// authoritative state.
		var next map[string]config.ProviderConfig
		if err := json.Unmarshal([]byte(*input.Providers), &next); err != nil {
			return nil, fmt.Errorf("invalid providers JSON: %w", err)
		}
		s.Providers = next
	}
	if input.Permissions != nil {
		if err := json.Unmarshal([]byte(*input.Permissions), &s.Permissions); err != nil {
			return nil, fmt.Errorf("invalid permissions JSON: %w", err)
		}
	}
	if input.McpServers != nil {
		if err := json.Unmarshal([]byte(*input.McpServers), &s.MCPServers); err != nil {
			return nil, fmt.Errorf("invalid MCP servers JSON: %w", err)
		}
	}
	if input.Hooks != nil {
		if err := json.Unmarshal([]byte(*input.Hooks), &s.Hooks); err != nil {
			return nil, fmt.Errorf("invalid hooks JSON: %w", err)
		}
	}
	if input.Preferences != nil {
		if err := json.Unmarshal([]byte(*input.Preferences), &s.Preferences); err != nil {
			return nil, fmt.Errorf("invalid preferences JSON: %w", err)
		}
	}
	if input.Engine != nil {
		var cfg config.EngineConfig
		if err := json.Unmarshal([]byte(*input.Engine), &cfg); err != nil {
			return nil, fmt.Errorf("invalid engine JSON: %w", err)
		}
		// Reject negatives at the boundary. Zero is a legitimate value
		// for every field (ScoreFloor=0 → no cutoff; EdgeThreshold=0 →
		// accept all edges; RadiusSize=0 → no radius pad; RerankTopK=0
		// → rerank disabled). Clamping on `> 0` would silently drop
		// valid zero-saves and create an "unset vs zero" ambiguity the
		// input shape doesn't carry.
		if cfg.EdgeThreshold < 0 ||
			cfg.ScoreFloor < 0 ||
			cfg.ZScoreThreshold < 0 || cfg.MinBatchStdDev < 0 ||
			cfg.RadiusSize < 0 || cfg.RerankTopK < 0 ||
			cfg.ContextBudgetTokens < 0 ||
			cfg.DiversityLambda < 0 || cfg.DiversityLambda > 1 ||
			cfg.BudgetHeadroomPct < 0 || cfg.BudgetHeadroomPct > 1 ||
			cfg.PerMsgDelimiterTokens < 0 {
			return nil, fmt.Errorf("engine config: negative values are not allowed; λ / headroom must be in [0,1]")
		}
		s.Engine = cfg
		// Apply to a fresh engine. Stored DAG edges are unchanged —
		// substrate.Build reloads them from disk; edge gating now uses
		// the stored CrossEncoderScore directly under current config.
		// Threshold tightening immediately hides edges that no longer
		// qualify. Loosening only surfaces edges that previously formed
		// at OnMessage time — chunk-pair scores below the old threshold
		// stayed in the score cache but produced no edge, and a fresh
		// rebuild from chunk_scores under the loosened threshold is
		// not wired here (separate concern).
		live := r.substrate.Engine().Config()
		live.EdgeThreshold = cfg.EdgeThreshold
		live.ScoreFloor = cfg.ScoreFloor
		live.ZScoreThreshold = cfg.ZScoreThreshold
		live.MinBatchStdDev = cfg.MinBatchStdDev
		live.RadiusSize = cfg.RadiusSize
		live.RerankTopK = cfg.RerankTopK
		live.ContextBudgetTokens = cfg.ContextBudgetTokens
		live.DiversityLambda = cfg.DiversityLambda
		live.BudgetHeadroomPct = cfg.BudgetHeadroomPct
		live.PerMsgDelimiterTokens = cfg.PerMsgDelimiterTokens
		if err := r.substrate.UpdateEngineConfig(ctx, live); err != nil {
			return nil, fmt.Errorf("update engine config: %w", err)
		}
		log.Printf("[Settings] Engine config applied live: thr=%.3f floor=%.3f z=%.2f minStd=%.3f radius=%d topK=%d budget=%d λ=%.2f headroom=%.2f delim=%d",
			live.EdgeThreshold,
			live.ScoreFloor,
			live.ZScoreThreshold, live.MinBatchStdDev,
			live.RadiusSize, live.RerankTopK,
			live.ContextBudgetTokens,
			live.DiversityLambda, live.BudgetHeadroomPct, live.PerMsgDelimiterTokens)
	}
	if err := r.cfg.Save(); err != nil {
		return nil, err
	}
	// Hot-reload providers from updated config
	if err := r.substrate.ReloadProviders(ctx); err != nil {
		log.Printf("[Settings] Provider reload: %v", err)
	}
	return r.Query().Settings(ctx)
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*Settings, error) {
	s := r.cfg.Settings
	providers, err := json.Marshal(s.Providers)
	if err != nil {
		return nil, fmt.Errorf("marshal providers: %w", err)
	}
	permissions, err := json.Marshal(s.Permissions)
	if err != nil {
		return nil, fmt.Errorf("marshal permissions: %w", err)
	}
	mcpServers, err := json.Marshal(s.MCPServers)
	if err != nil {
		return nil, fmt.Errorf("marshal mcp servers: %w", err)
	}
	hooks, err := json.Marshal(s.Hooks)
	if err != nil {
		return nil, fmt.Errorf("marshal hooks: %w", err)
	}
	preferences, err := json.Marshal(s.Preferences)
	if err != nil {
		return nil, fmt.Errorf("marshal preferences: %w", err)
	}
	// Serialize engine config from the currently-live engine, not from
	// config file. This lets the UI reflect the actual operating
	// config (including any defaults that kicked in when Settings had
	// zero-value engine fields).
	engineCfg := r.substrate.Engine().Config()
	engine, err := json.Marshal(map[string]any{
		"edge_threshold":           engineCfg.EdgeThreshold,
		"score_floor":              engineCfg.ScoreFloor,
		"z_score_threshold":        engineCfg.ZScoreThreshold,
		"min_batch_stddev":         engineCfg.MinBatchStdDev,
		"radius_size":              engineCfg.RadiusSize,
		"rerank_top_k":             engineCfg.RerankTopK,
		"context_budget_tokens":    engineCfg.ContextBudgetTokens,
		"diversity_lambda":         engineCfg.DiversityLambda,
		"budget_headroom_pct":      engineCfg.BudgetHeadroomPct,
		"per_msg_delimiter_tokens": engineCfg.PerMsgDelimiterTokens,
	})
	if err != nil {
		return nil, fmt.Errorf("marshal engine config: %w", err)
	}
	return &Settings{
		Providers:   string(providers),
		Permissions: string(permissions),
		McpServers:  string(mcpServers),
		Hooks:       string(hooks),
		Preferences: string(preferences),
		Engine:      string(engine),
	}, nil
}

// Skills is the resolver for the skills field.
func (r *queryResolver) Skills(ctx context.Context) ([]*SkillInfo, error) {
	loaded := r.Resolver.skills
	result := make([]*SkillInfo, len(loaded))
	for i, s := range loaded {
		result[i] = &SkillInfo{Name: s.Name, Description: s.Description}
	}
	return result, nil
}
