package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log"

	"github.com/elijahmontenegro/grudge/service/config"
	"github.com/elijahmontenegro/grudge/service/hooks"
	"github.com/elijahmontenegro/grudge/service/mcp"
)

// UpdateSettings is the resolver for the updateSettings field.
//
// Decode and validate everything FIRST, then apply the whole snapshot
// in one holder-locked mutation with one rebuild. Writing cfg.Settings
// fields inline (the old shape) races the background calibration
// stages, which re-enter Build and read cfg.Settings under the
// holder's lock at arbitrary moments.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input SettingsInput) (*Settings, error) {
	var providers map[string]config.ProviderConfig
	if input.Providers != nil {
		// Replace semantics, not merge. `json.Unmarshal` into an
		// existing map preserves keys the new payload omits; that
		// meant removing a provider in the UI never actually removed
		// it from disk. Decoding into a fresh map keeps the input the
		// authoritative state.
		if err := json.Unmarshal([]byte(*input.Providers), &providers); err != nil {
			return nil, fmt.Errorf("invalid providers JSON: %w", err)
		}
	}
	var permissions map[string]string
	if input.Permissions != nil {
		if err := json.Unmarshal([]byte(*input.Permissions), &permissions); err != nil {
			return nil, fmt.Errorf("invalid permissions JSON: %w", err)
		}
	}
	var mcpServers []mcp.ServerConfig
	if input.McpServers != nil {
		if err := json.Unmarshal([]byte(*input.McpServers), &mcpServers); err != nil {
			return nil, fmt.Errorf("invalid MCP servers JSON: %w", err)
		}
	}
	var hookConfigs []hooks.HookConfig
	if input.Hooks != nil {
		if err := json.Unmarshal([]byte(*input.Hooks), &hookConfigs); err != nil {
			return nil, fmt.Errorf("invalid hooks JSON: %w", err)
		}
	}
	var preferences map[string]string
	if input.Preferences != nil {
		if err := json.Unmarshal([]byte(*input.Preferences), &preferences); err != nil {
			return nil, fmt.Errorf("invalid preferences JSON: %w", err)
		}
	}
	var engine *config.EngineConfig
	if input.Engine != nil {
		var cfg config.EngineConfig
		decoder := json.NewDecoder(bytes.NewReader([]byte(*input.Engine)))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&cfg); err != nil {
			return nil, fmt.Errorf("invalid engine JSON: %w", err)
		}
		if err := cfg.Validate(); err != nil {
			return nil, err
		}
		engine = &cfg
	}

	if err := r.substrate.MutateSettings(ctx, func(s *config.Settings) error {
		if input.Providers != nil {
			s.Providers = providers
		}
		if input.Permissions != nil {
			s.Permissions = permissions
		}
		if input.McpServers != nil {
			s.MCPServers = mcpServers
		}
		if input.Hooks != nil {
			s.Hooks = hookConfigs
		}
		if input.Preferences != nil {
			s.Preferences = preferences
		}
		if engine != nil {
			// loss_ratio 0 on the wire means "keep the current stance" —
			// persist the kept value, not the zero, so the stance
			// survives the round-trip.
			if engine.LossRatio == 0 {
				engine.LossRatio = s.Engine.LossRatio
			}
			s.Engine = *engine
		}
		return nil
	}); err != nil {
		return nil, fmt.Errorf("apply settings: %w", err)
	}

	if engine != nil {
		live := r.substrate.Engine().Config()
		log.Printf("[Settings] Engine config applied live: lossRatio=%.3f minStd=%.3f local=%d topK=%d budget=%d lambda=%.2f headroom=%.2f delim=%d",
			live.LossRatio, live.MinBatchStdDev,
			live.LocalContextSize, live.RerankTopK,
			live.ContextBudgetTokens,
			live.DiversityLambda, live.BudgetHeadroomPct, live.PerMsgDelimiterTokens)
	}
	return r.Query().Settings(ctx)
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*Settings, error) {
	s := r.cfg.Settings
	providers, err := json.Marshal(s.Providers)
	if err != nil {
		return nil, fmt.Errorf("marshal providers: %w", err)
	}
	permissions, err := json.Marshal(s.Permissions)
	if err != nil {
		return nil, fmt.Errorf("marshal permissions: %w", err)
	}
	mcpServers, err := json.Marshal(s.MCPServers)
	if err != nil {
		return nil, fmt.Errorf("marshal mcp servers: %w", err)
	}
	hooks, err := json.Marshal(s.Hooks)
	if err != nil {
		return nil, fmt.Errorf("marshal hooks: %w", err)
	}
	preferences, err := json.Marshal(s.Preferences)
	if err != nil {
		return nil, fmt.Errorf("marshal preferences: %w", err)
	}
	// Serialize engine config from the currently-live engine, not from
	// config file. This lets the UI reflect the actual operating
	// config (including any defaults that kicked in when Settings had
	// zero-value engine fields).
	engine, err := json.Marshal(config.EngineConfigFromRRC(r.substrate.Engine().Config()))
	if err != nil {
		return nil, fmt.Errorf("marshal engine config: %w", err)
	}
	return &Settings{
		Providers:   string(providers),
		Permissions: string(permissions),
		McpServers:  string(mcpServers),
		Hooks:       string(hooks),
		Preferences: string(preferences),
		Engine:      string(engine),
	}, nil
}

// Skills is the resolver for the skills field.
func (r *queryResolver) Skills(ctx context.Context) ([]*SkillInfo, error) {
	loaded := r.Resolver.skills
	result := make([]*SkillInfo, len(loaded))
	for i, s := range loaded {
		result[i] = &SkillInfo{Name: s.Name, Description: s.Description}
	}
	return result, nil
}
