package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	pb "github.com/emontenegr/spidey/proto/gen/go/spidey/v1"
	"github.com/emontenegr/spidey/rrc"
	"github.com/emontenegr/spidey/service/internal/adoc"
	"github.com/emontenegr/spidey/service/config"
	"github.com/emontenegr/spidey/service/storage"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// Score is the resolver for the score field.
func (r *edgeResolver) Score(ctx context.Context, obj *pb.Edge) (float64, error) {
	return float64(obj.Score), nil
}

// Source is the resolver for the source field.
func (r *edgeResolver) Source(ctx context.Context, obj *pb.Edge) (string, error) {
	return obj.Source.String(), nil
}

// CrossEncoderScore is the resolver for the crossEncoderScore field.
func (r *edgeResolver) CrossEncoderScore(ctx context.Context, obj *pb.Edge) (float64, error) {
	return float64(obj.CrossEncoderScore), nil
}

// TemporalProximity is the resolver for the temporalProximity field.
func (r *edgeResolver) TemporalProximity(ctx context.Context, obj *pb.Edge) (float64, error) {
	return float64(obj.TemporalProximity), nil
}

// Reason is the resolver for the reason field.
func (r *excludedMessageResolver) Reason(ctx context.Context, obj *pb.ExcludedMessage) (string, error) {
	return obj.Reason.String(), nil
}

// Score is the resolver for the score field.
func (r *excludedMessageResolver) Score(ctx context.Context, obj *pb.ExcludedMessage) (float64, error) {
	return float64(obj.Score), nil
}

// Role is the resolver for the role field.
func (r *messageResolver) Role(ctx context.Context, obj *pb.Message) (string, error) {
	return protoRoleToDisplay(obj.Role), nil
}

// Content is the resolver for the content field.
func (r *messageResolver) Content(ctx context.Context, obj *pb.Message) (string, error) {
	return protoContentToDisplay(obj.Content), nil
}

// Thinking is the resolver for the thinking field.
func (r *messageResolver) Thinking(ctx context.Context, obj *pb.Message) (*string, error) {
	thinking := protoThinkingContent(obj.Content)
	if thinking == "" {
		return nil, nil
	}
	return &thinking, nil
}

// ToolCalls is the resolver for the toolCalls field.
func (r *messageResolver) ToolCalls(ctx context.Context, obj *pb.Message) ([]*ToolCallBlock, error) {
	calls := protoToolCalls(obj.Content)
	result := make([]*ToolCallBlock, len(calls))
	for i, tc := range calls {
		result[i] = &ToolCallBlock{ID: tc.Id, Name: tc.Name, Arguments: tc.Arguments}
	}
	return result, nil
}

// ToolResults is the resolver for the toolResults field.
func (r *messageResolver) ToolResults(ctx context.Context, obj *pb.Message) ([]*ToolResultBlock, error) {
	results := protoToolResults(obj.Content)
	out := make([]*ToolResultBlock, len(results))
	for i, tr := range results {
		out[i] = &ToolResultBlock{ToolCallID: tr.ToolCallId, Content: tr.Content}
	}
	return out, nil
}

// Attachments is the resolver for the attachments field. Walks the
// message's content blocks and surfaces any AttachmentContent as
// metadata-only blocks (the actual file bytes stay in the workspace;
// GraphQL returns references, clients fetch via the HTTP endpoint).
func (r *messageResolver) Attachments(ctx context.Context, obj *pb.Message) ([]*AttachmentBlock, error) {
	var out []*AttachmentBlock
	for _, b := range obj.Content {
		if a := b.GetAttachment(); a != nil {
			out = append(out, &AttachmentBlock{
				ID:        a.Id,
				Filename:  a.Filename,
				MimeType:  a.MimeType,
				SizeBytes: int(a.SizeBytes),
				Path:      a.Path,
			})
		}
	}
	return out, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *messageResolver) CreatedAt(ctx context.Context, obj *pb.Message) (*time.Time, error) {
	if obj.CreatedAt != nil {
		t := obj.CreatedAt.AsTime()
		return &t, nil
	}
	return nil, nil
}

// CitedByCount is the resolver for the citedByCount field.
func (r *messageResolver) CitedByCount(ctx context.Context, obj *pb.Message) (int, error) {
	return r.CitationCount(obj.Id), nil
}

// CreateThread is the resolver for the createThread field.
func (r *mutationResolver) CreateThread(ctx context.Context, name *string, workingDirs []string, sandboxed *bool) (*pb.Thread, error) {
	threadName := ""
	if name != nil {
		threadName = *name
	}
	// Auto-set working directory to CWD if none provided
	if len(workingDirs) == 0 {
		if cwd, err := os.Getwd(); err == nil {
			workingDirs = []string{cwd}
		}
	}
	// Default to sandboxed=true when unset: Bash + file tools are
	// confined to a per-thread workspace via sandbox.WorkspaceDir.
	// Protects the host from prompt-injected commands that would
	// otherwise read keys / overwrite arbitrary files. Callers can
	// pass sandboxed=false at creation for threads that genuinely
	// need host access.
	sbx := true
	if sandboxed != nil {
		sbx = *sandboxed
	}
	t := &pb.Thread{
		Id:          fmt.Sprintf("thread-%d", time.Now().UnixNano()),
		Name:        threadName,
		WorkingDirs: workingDirs,
		Sandboxed:   sbx,
		CreatedAt:   timestamppb.Now(),
	}
	if err := r.DB.CreateThread(t); err != nil {
		return nil, err
	}
	r.publishThreadState(&ThreadStateEvent{ThreadID: t.Id, Name: t.Name, Status: AgentStatusIdle, Mode: AgentModeNormal})
	return t, nil
}

// UpdateThread is the resolver for the updateThread field.
func (r *mutationResolver) UpdateThread(ctx context.Context, id string, name *string, workingDirs []string, sandboxed *bool) (*pb.Thread, error) {
	t, err := r.DB.GetThread(id)
	if err != nil {
		return nil, err
	}
	if name != nil {
		t.Name = *name
	}
	if workingDirs != nil {
		t.WorkingDirs = workingDirs
	}
	if sandboxed != nil {
		t.Sandboxed = *sandboxed
	}
	if err := r.DB.UpdateThread(t); err != nil {
		return nil, err
	}
	return t, nil
}

// DeleteThread is the resolver for the deleteThread field.
func (r *mutationResolver) DeleteThread(ctx context.Context, id string) (bool, error) {
	if err := r.DB.DeleteThread(id); err != nil {
		return false, err
	}
	r.DB.DeleteEdgesForThread(id)
	r.publishThreadState(&ThreadStateEvent{ThreadID: id})
	return true, nil
}

// ArchiveThread is the resolver for the archiveThread field.
func (r *mutationResolver) ArchiveThread(ctx context.Context, id string) (bool, error) {
	if err := r.DB.ArchiveThread(id); err != nil {
		return false, err
	}
	r.publishThreadState(&ThreadStateEvent{ThreadID: id})
	return true, nil
}

// UnarchiveThread is the resolver for the unarchiveThread field.
func (r *mutationResolver) UnarchiveThread(ctx context.Context, id string) (bool, error) {
	if err := r.DB.UnarchiveThread(id); err != nil {
		return false, err
	}
	r.publishThreadState(&ThreadStateEvent{ThreadID: id})
	return true, nil
}

// EditMessage is the resolver for the editMessage field.
func (r *mutationResolver) EditMessage(ctx context.Context, threadID string, messagePosition int, newContent string) (*pb.Thread, error) {
	parentThread, err := r.DB.GetThread(threadID)
	if err != nil {
		return nil, err
	}

	branchPos := int64(messagePosition)
	newThread := &pb.Thread{
		Id:                  fmt.Sprintf("thread-%d", time.Now().UnixNano()),
		Name:                parentThread.Name + " (branch)",
		WorkingDirs:         parentThread.WorkingDirs,
		Sandboxed:           parentThread.Sandboxed,
		CreatedAt:           timestamppb.Now(),
		ParentThreadId:      &threadID,
		BranchPointPosition: &branchPos,
	}
	if err := r.DB.CreateThread(newThread); err != nil {
		return nil, err
	}

	// No Engine.Fork needed — the global engine has the parent's edges and scores.
	// ThreadCorpus for the branch includes the parent's messages up to the branch point
	// (referenced, not copied). OnMessage will score the new message against the full
	// inherited corpus. Edges for the parent's messages are already in the DAG.

	// Insert the edited message at the branch point
	msg := &pb.Message{
		Id:       fmt.Sprintf("msg-%s-0", newThread.Id),
		Role:     pb.Role_ROLE_USER,
		Content:  rrc.BlocksFromText(newContent),
		Position: int64(messagePosition),
		ThreadId: newThread.Id,
	}
	if err := r.storeMessage(msg, newContent); err != nil {
		return nil, err
	}

	return newThread, nil
}

// CompileAdoc is the resolver for the compileAdoc field.
func (r *mutationResolver) CompileAdoc(ctx context.Context, path string) (string, error) {
	return adoc.Compile(path)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, threadID string, content string, scope *SelectionScope, attachments []*AttachmentInput) (*pb.Message, error) {
	// Auto-name thread from first user message
	corpus, err := r.DB.ThreadCorpus(threadID)
	if err != nil {
		return nil, fmt.Errorf("load corpus: %w", err)
	}
	if len(corpus) == 0 && content != "" {
		if err := r.DB.UpdateThreadName(threadID, storage.TruncateThreadName(content)); err != nil {
			return nil, fmt.Errorf("update thread name: %w", err)
		}
	}

	runner, err := r.getOrCreateRunner(threadID)
	if err != nil {
		return nil, fmt.Errorf("get runner: %w", err)
	}
	// Default scope is all-threads. The whole point of RRC is that
	// the user's prior conversations (any thread) can be pulled in when
	// relevant. Thread-only is the opt-out, not the default — the old
	// default made the agent look amnesiac ("I don't retain info across
	// chats") because it literally had no cross-thread context to pull.
	pbScope := pb.SelectionScope_SELECTION_SCOPE_ALL_THREADS
	if scope != nil && *scope == SelectionScopeThread {
		pbScope = pb.SelectionScope_SELECTION_SCOPE_THREAD
	}

	// Defer a publish of Status=Idle so the UI doesn't get stuck showing
	// "running" after the turn ends. ExitPlan's AgentState("normal")
	// callback flips Status=Running mid-turn; without this defer, that
	// state would persist until the user takes an explicit action like
	// stop or approve. Read current mode from DB so we don't clobber it.
	defer func() {
		st, err := r.DB.GetAgentState(threadID)
		if err != nil {
			return
		}
		gqlMode := AgentModeNormal
		switch st.Mode {
		case storage.AgentModePlan:
			gqlMode = AgentModePlan
		case storage.AgentModeAutonomous:
			gqlMode = AgentModeAutonomous
		}
		// Don't clobber autonomous-in-progress — that loop publishes its
		// own Idle on exit via defer in StartAutonomous.
		if st.Mode == storage.AgentModeAutonomous && st.Status == storage.AgentStatusRunning {
			return
		}
		var planPtr *string
		if pc := r.GetPlan(threadID); pc != "" {
			planPtr = &pc
		}
		// Narrow UPDATE (round 93 helper) so we don't wipe StartedAt /
		// DurationLimit that an autonomous run may have set. Mode is
		// already whatever it was — SetAgentStatus leaves it alone.
		if err := r.DB.SetAgentStatus(threadID, storage.AgentStatusIdle); err == nil {
			r.publishAgentState(threadID, &AgentState{
				ThreadID: threadID, Status: AgentStatusIdle, Mode: gqlMode,
				PlanContent: planPtr,
			})
		}
	}()

	// Filenames / sizes / paths are server-generated during upload
	// and echoed back, so no re-validation is needed at this boundary
	// (the files already exist on disk in the workspace).
	attachBlocks := attachmentInputsToBlocks(attachments)

	resp, err := runner.SendMessage(ctx, content, pbScope, attachBlocks...)
	if err != nil {
		return nil, fmt.Errorf("send message: %w", err)
	}
	return resp, nil
}

// StopAgent is the resolver for the stopAgent field.
func (r *mutationResolver) StopAgent(ctx context.Context, threadID string) (bool, error) {
	r.stopRunner(threadID)
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModeNormal,
	})
	if err := r.DB.EnsureAgentStateRow(threadID, storage.AgentStatusIdle, storage.AgentModeNormal); err != nil {
		return false, err
	}
	return true, r.DB.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModeNormal)
}

// PauseAgent is the resolver for the pauseAgent field.
func (r *mutationResolver) PauseAgent(ctx context.Context, threadID string) (bool, error) {
	if entry, ok := r.Runners.Get(threadID); ok {
		entry.Runner.PauseAutonomous()
	}
	st, err := r.DB.GetAgentState(threadID)
	if err != nil {
		return false, fmt.Errorf("load state: %w", err)
	}
	gqlMode := AgentModeNormal
	switch st.Mode {
	case storage.AgentModePlan:
		gqlMode = AgentModePlan
	case storage.AgentModeAutonomous:
		gqlMode = AgentModeAutonomous
	}
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusPaused, Mode: gqlMode,
	})
	return true, r.DB.SetAgentStatus(threadID, storage.AgentStatusPaused)
}

// ResumeAgent is the resolver for the resumeAgent field.
func (r *mutationResolver) ResumeAgent(ctx context.Context, threadID string, correction *string) (bool, error) {
	if correction != nil && *correction != "" {
		corpus, err := r.DB.ThreadCorpus(threadID)
		if err != nil {
			return false, fmt.Errorf("load corpus: %w", err)
		}
		msg := &pb.Message{
			Id:        fmt.Sprintf("msg-%d", time.Now().UnixNano()),
			Role:      pb.Role_ROLE_USER,
			Content:   rrc.BlocksFromText(*correction),
			Position:  int64(len(corpus)),
			ThreadId:  threadID,
			CreatedAt: timestamppb.Now(),
		}
		if err := r.storeMessage(msg, *correction); err != nil {
			return false, fmt.Errorf("insert correction: %w", err)
		}
	}
	// Same full-row UPSERT concern as PauseAgent — preserve Mode/RoundCount
	// rather than zeroing them via a partial state save.
	st, err := r.DB.GetAgentState(threadID)
	if err != nil {
		return false, fmt.Errorf("load state: %w", err)
	}
	// Two resume paths:
	//   (a) Active autonomous loop, just paused → flip the pause gate.
	//   (b) Dead autonomous loop (runner exited, e.g. ctx cancel) but DB
	//       still has Mode=Autonomous → kick a fresh RunAutonomous
	//       goroutine so the UX doesn't lie.
	entry, haveEntry := r.Runners.Get(threadID)
	restartedAutonomous := false
	if haveEntry && entry.Runner.IsAutonomousActive() {
		entry.Runner.ResumeAutonomous()
	} else if st.Mode == storage.AgentModeAutonomous {
		remaining, reason := st.RemainingBudget()
		if reason == "" && remaining > 0 {
			runner, rerr := r.getOrCreateRunner(threadID)
			if rerr != nil {
				return false, fmt.Errorf("restart runner: %w", rerr)
			}
			autoCtx, autoCancel := context.WithCancel(context.Background())
			r.Runners.SetCancel(threadID, autoCancel)
			// Continuation prompt — non-empty so the model gets a
			// clear directive rather than inferring from RRC alone.
			// If the caller supplied a correction it's already been
			// stored above; the "continue" kickoff still picks it up
			// via Selection on the first round.
			kickoff := "continue"
			if correction != nil && *correction != "" {
				kickoff = *correction
			}
			go func() {
				defer r.stopRunner(threadID)
				defer r.DB.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModeNormal)
				defer r.publishAgentState(threadID, &AgentState{ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModeNormal})
				if err := runner.RunAutonomous(autoCtx, kickoff, remaining); err != nil {
					log.Printf("[Autonomous resumed] Error: %v", err)
				}
			}()
			restartedAutonomous = true
		}
	}
	gqlMode := AgentModeNormal
	switch st.Mode {
	case storage.AgentModePlan:
		gqlMode = AgentModePlan
	case storage.AgentModeAutonomous:
		gqlMode = AgentModeAutonomous
	}
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusRunning, Mode: gqlMode,
	})
	_ = restartedAutonomous
	return true, r.DB.SetAgentStatus(threadID, storage.AgentStatusRunning)
}

// StartAutonomous is the resolver for the startAutonomous field.
func (r *mutationResolver) StartAutonomous(ctx context.Context, threadID string, prompt string, duration string, attachments []*AttachmentInput) (bool, error) {
	dur, err := time.ParseDuration(duration)
	if err != nil {
		return false, fmt.Errorf("invalid duration: %w", err)
	}
	const minDur = 5 * time.Minute
	const maxDur = 14 * 24 * time.Hour
	if dur < minDur {
		return false, fmt.Errorf("minimum autonomous duration is 5m")
	}
	if dur > maxDur {
		dur = maxDur
	}
	now := time.Now()
	if err := r.DB.StartAutonomousRun(threadID, now, duration); err != nil {
		return false, err
	}

	// Launch the autonomous loop in a goroutine
	runner, err := r.getOrCreateRunner(threadID)
	if err != nil {
		return false, fmt.Errorf("create runner: %w", err)
	}
	autoCtx, autoCancel := context.WithCancel(context.Background())
	r.Runners.SetCancel(threadID, autoCancel)

	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusRunning, Mode: AgentModeAutonomous,
		RoundCount: 0, DurationLimit: &duration,
	})

	go func() {
		defer r.stopRunner(threadID)
		defer r.DB.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModeNormal)
		defer r.publishAgentState(threadID, &AgentState{
			ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModeNormal,
		})
		if err := runner.RunAutonomous(autoCtx, prompt, dur, attachmentInputsToBlocks(attachments)...); err != nil {
			log.Printf("[Autonomous] Error: %v", err)
		}
	}()

	return true, nil
}

// ApproveToolCall is the resolver for the approveToolCall field.
func (r *mutationResolver) ApproveToolCall(ctx context.Context, callID string) (bool, error) {
	if !r.SendApproval(callID, true) {
		return false, fmt.Errorf("no pending approval for call %s", callID)
	}
	return true, nil
}

// DenyToolCall is the resolver for the denyToolCall field.
func (r *mutationResolver) DenyToolCall(ctx context.Context, callID string, reason *string) (bool, error) {
	threadID := r.ThreadIDForCall(callID)
	// Inject denial feedback as a system message — the user's denial reason is
	// operational context for the model, not a user utterance. It belongs in the
	// system domain, not the conversation.
	if reason != nil && *reason != "" && threadID != "" {
		corpus, _ := r.DB.ThreadCorpus(threadID)
		denialText := fmt.Sprintf("Tool call denied by user. Reason: %s", *reason)
		msg := &pb.Message{
			Id:        fmt.Sprintf("msg-%d", time.Now().UnixNano()),
			Role:      pb.Role_ROLE_SYSTEM,
			Content:   rrc.BlocksFromText(denialText),
			Position:  int64(len(corpus)),
			ThreadId:  threadID,
			CreatedAt: timestamppb.Now(),
		}
		_ = r.storeMessage(msg, denialText)
	}
	if !r.SendApproval(callID, false) {
		return false, fmt.Errorf("no pending approval for call %s", callID)
	}
	return true, nil
}

// AnswerQuestion is the resolver for the answerQuestion field.
func (r *mutationResolver) AnswerQuestion(ctx context.Context, callID string, answer string) (bool, error) {
	if !r.SendAnswer(callID, answer) {
		return false, fmt.Errorf("no pending question for call %s", callID)
	}
	return true, nil
}

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input SettingsInput) (*Settings, error) {
	s := &r.Config.Settings
	if input.Providers != nil {
		// Replace semantics, not merge. `json.Unmarshal` into an
		// existing map preserves keys the new payload omits; that
		// meant removing a provider in the UI never actually removed
		// it from disk. Zero the map first so the input is the
		// authoritative state.
		var next map[string]config.ProviderConfig
		if err := json.Unmarshal([]byte(*input.Providers), &next); err != nil {
			return nil, fmt.Errorf("invalid providers JSON: %w", err)
		}
		s.Providers = next
	}
	if input.Permissions != nil {
		if err := json.Unmarshal([]byte(*input.Permissions), &s.Permissions); err != nil {
			return nil, fmt.Errorf("invalid permissions JSON: %w", err)
		}
	}
	if input.McpServers != nil {
		if err := json.Unmarshal([]byte(*input.McpServers), &s.MCPServers); err != nil {
			return nil, fmt.Errorf("invalid MCP servers JSON: %w", err)
		}
	}
	if input.Hooks != nil {
		if err := json.Unmarshal([]byte(*input.Hooks), &s.Hooks); err != nil {
			return nil, fmt.Errorf("invalid hooks JSON: %w", err)
		}
	}
	if input.Preferences != nil {
		if err := json.Unmarshal([]byte(*input.Preferences), &s.Preferences); err != nil {
			return nil, fmt.Errorf("invalid preferences JSON: %w", err)
		}
	}
	if input.Engine != nil {
		var cfg config.EngineConfig
		if err := json.Unmarshal([]byte(*input.Engine), &cfg); err != nil {
			return nil, fmt.Errorf("invalid engine JSON: %w", err)
		}
		// Reject negatives at the boundary. Zero is a legitimate value
		// for every field (ScoreFloor=0 → no cutoff; EdgeThreshold=0 →
		// accept all edges; RadiusSize=0 → no radius pad; RerankTopK=0
		// → rerank disabled). Clamping on `> 0` would silently drop
		// valid zero-saves and create an "unset vs zero" ambiguity the
		// input shape doesn't carry.
		if cfg.EdgeThreshold < 0 ||
			cfg.ScoreFloor < 0 ||
			cfg.ZScoreThreshold < 0 || cfg.MinBatchStdDev < 0 ||
			cfg.RadiusSize < 0 || cfg.RerankTopK < 0 ||
			cfg.ContextBudgetTokens < 0 ||
			cfg.DiversityLambda < 0 || cfg.DiversityLambda > 1 ||
			cfg.BudgetHeadroomPct < 0 || cfg.BudgetHeadroomPct > 1 ||
			cfg.PerMsgDelimiterTokens < 0 {
			return nil, fmt.Errorf("engine config: negative values are not allowed; λ / headroom must be in [0,1]")
		}
		s.Engine = cfg
		// Apply to a fresh engine. Stored DAG edges are unchanged —
		// substrate.Build reloads them from disk; edge gating now uses
		// the stored CrossEncoderScore directly under current config.
		// Threshold tightening immediately hides edges that no longer
		// qualify. Loosening only surfaces edges that previously formed
		// at OnMessage time — chunk-pair scores below the old threshold
		// stayed in the score cache but produced no edge, and a fresh
		// rebuild from chunk_scores under the loosened threshold is
		// not wired here (separate concern).
		live := r.Engine().Config()
		live.EdgeThreshold = cfg.EdgeThreshold
		live.ScoreFloor = cfg.ScoreFloor
		live.ZScoreThreshold = cfg.ZScoreThreshold
		live.MinBatchStdDev = cfg.MinBatchStdDev
		live.RadiusSize = cfg.RadiusSize
		live.RerankTopK = cfg.RerankTopK
		live.ContextBudgetTokens = cfg.ContextBudgetTokens
		live.DiversityLambda = cfg.DiversityLambda
		live.BudgetHeadroomPct = cfg.BudgetHeadroomPct
		live.PerMsgDelimiterTokens = cfg.PerMsgDelimiterTokens
		if err := r.UpdateEngineConfig(ctx, live); err != nil {
			return nil, fmt.Errorf("update engine config: %w", err)
		}
		log.Printf("[Settings] Engine config applied live: thr=%.3f floor=%.3f z=%.2f minStd=%.3f radius=%d topK=%d budget=%d λ=%.2f headroom=%.2f delim=%d",
			live.EdgeThreshold,
			live.ScoreFloor,
			live.ZScoreThreshold, live.MinBatchStdDev,
			live.RadiusSize, live.RerankTopK,
			live.ContextBudgetTokens,
			live.DiversityLambda, live.BudgetHeadroomPct, live.PerMsgDelimiterTokens)
	}
	if err := r.Config.Save(); err != nil {
		return nil, err
	}
	// Hot-reload providers from updated config
	if err := r.ReloadProviders(ctx); err != nil {
		log.Printf("[Settings] Provider reload: %v", err)
	}
	return r.Query().Settings(ctx)
}

// EnterPlanMode is the resolver for the enterPlanMode field.
// Plan mode is a permission/intent state, NOT an execution status — flipping
// the composer pill to "plan" without sending anything must not make the UI
// claim "agent is running." Keep Status=Idle; Mode=Plan. The runner still
// gets restarted so the plan-mode system prompt is reassembled for the next
// SendMessage. Mirrors claude-code's model where plan mode is a
// toolPermissionContext.mode flag, not an agent status.
func (r *mutationResolver) EnterPlanMode(ctx context.Context, threadID string) (bool, error) {
	if err := r.DB.EnsureAgentStateRow(threadID, storage.AgentStatusIdle, storage.AgentModePlan); err != nil {
		return false, err
	}
	if err := r.DB.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModePlan); err != nil {
		return false, err
	}
	// Stop existing runner so a fresh one is created with plan mode prompt
	r.stopRunner(threadID)
	// Creating the runner now picks up mode=plan from DB, assembles plan mode system prompt
	if _, err := r.getOrCreateRunner(threadID); err != nil {
		return false, fmt.Errorf("create runner: %w", err)
	}
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModePlan,
	})
	return true, nil
}

// ApprovePlan is the resolver for the approvePlan field.
// For Manual mode: clears plan content + flips mode to Normal. Status stays
// Idle since nothing is actively running — the model will implement on the
// user's next message (or they can ask for specific changes). Publishing
// Running here would phantom-signal activity just like round-120's
// EnterPlanMode bug.
// For Autonomous mode: same state changes, plus kicks a RunAutonomous
// goroutine with an "implement the plan" prompt. Status=Running there
// because the goroutine actually runs.
func (r *mutationResolver) ApprovePlan(ctx context.Context, threadID string, executionMode ExecutionMode) (bool, error) {
	stMode := storage.AgentModeNormal
	gqlMode := AgentModeNormal
	if executionMode == ExecutionModeAutonomous {
		stMode = storage.AgentModeAutonomous
		gqlMode = AgentModeAutonomous
	}
	// Manual: Idle (nothing running). Autonomous: Running (goroutine below).
	stStatus := storage.AgentStatusIdle
	gqlStatus := AgentStatusIdle
	if executionMode == ExecutionModeAutonomous {
		stStatus = storage.AgentStatusRunning
		gqlStatus = AgentStatusRunning
	}
	if err := r.DB.EnsureAgentStateRow(threadID, stStatus, stMode); err != nil {
		return false, err
	}
	if err := r.DB.SetAgentStatusAndMode(threadID, stStatus, stMode); err != nil {
		return false, err
	}
	// Clear plan content — it's been approved and enters the corpus
	r.ClearPlan(threadID)
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: gqlStatus, Mode: gqlMode,
	})

	if executionMode == ExecutionModeAutonomous {
		// Kick an autonomous loop so "approve · autonomous" actually does
		// something. Default duration 1h — the PlanPanel's autonomous
		// approve button doesn't currently pass a duration; we use a sane
		// default and let the user stop/extend via the topbar controls.
		const defaultDuration = "1h"
		dur, _ := time.ParseDuration(defaultDuration)
		runner, err := r.getOrCreateRunner(threadID)
		if err != nil {
			return false, fmt.Errorf("create runner: %w", err)
		}
		autoCtx, autoCancel := context.WithCancel(context.Background())
		r.Runners.SetCancel(threadID, autoCancel)
		go func() {
			defer r.stopRunner(threadID)
			defer r.DB.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModeNormal)
			defer r.publishAgentState(threadID, &AgentState{
				ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModeNormal,
			})
			// Non-empty prompt so the model gets a concrete directive — an
			// empty-content user turn would leave it inferring from RRC
			// selection alone, which is less reliable for a post-approval
			// handoff. The model already has the approved plan in context
			// (ExitPlan tool_result + plan.adoc on disk), but naming the
			// transition explicitly is cheap and unambiguous.
			const approvedPrompt = "Plan approved. Proceed with implementation. Re-read plan.adoc if any detail is unclear."
			if err := runner.RunAutonomous(autoCtx, approvedPrompt, dur); err != nil {
				log.Printf("[Autonomous plan-approved] Error: %v", err)
			}
		}()
	}
	return true, nil
}

// RejectPlan is the resolver for the rejectPlan field.
// Clears stored plan content, re-enters plan mode with a fresh runner so the
// plan-mode system prompt is re-applied, and publishes cleared agent state
// so the PlanPanel closes. The caller is expected to follow up with a
// sendMessage carrying the feedback so the model revises plan.adoc.
func (r *mutationResolver) RejectPlan(ctx context.Context, threadID string, feedback *string) (bool, error) {
	r.ClearPlan(threadID)

	// Status stays Idle — rejectPlan itself doesn't execute a round. The
	// follow-up sendMessage carrying the feedback is what actually kicks
	// the revision round; its streaming surfaces via the usual path.
	if err := r.DB.EnsureAgentStateRow(threadID, storage.AgentStatusIdle, storage.AgentModePlan); err != nil {
		return false, err
	}
	if err := r.DB.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModePlan); err != nil {
		return false, err
	}
	// Stop the current runner so the next getOrCreateRunner picks up plan
	// mode and rebuilds the system prompt from scratch (no stale plan in it).
	r.stopRunner(threadID)
	if _, err := r.getOrCreateRunner(threadID); err != nil {
		return false, fmt.Errorf("create runner: %w", err)
	}
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModePlan,
		PlanContent: nil,
	})
	_ = feedback // reserved for future inline-feedback injection; caller currently sends feedback via sendMessage
	return true, nil
}

// UpdatePlanSource is the resolver for the updatePlanSource field.
// Overwrites plan.adoc with user-edited content before approval. Updates the
// in-memory plan-content cache and re-publishes agentState so the PlanPanel
// re-renders with the edited version. The model will see the new content on
// its next FileRead of plan.adoc.
func (r *mutationResolver) UpdatePlanSource(ctx context.Context, threadID string, content string) (bool, error) {
	planDir, err := storage.PlanDirForThread(r.Config.DataDir, threadID)
	if err != nil {
		return false, err
	}
	planPath := filepath.Join(planDir, "plan.adoc")
	if err := os.MkdirAll(planDir, 0o755); err != nil {
		return false, fmt.Errorf("ensure plan dir: %w", err)
	}
	if err := os.WriteFile(planPath, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("write plan: %w", err)
	}
	r.SetPlan(threadID, content)

	// Re-publish agentState with the fresh plan content. Preserve whatever
	// status/mode the runner is currently reporting — editing the plan is
	// an out-of-band user action, not a state transition.
	st, err := r.DB.GetAgentState(threadID)
	if err != nil {
		// State missing is non-fatal here — the file write already succeeded
		// and a subsequent approve/reject will re-publish with sane defaults.
		return true, nil
	}
	gqlStatus := AgentStatusIdle
	switch st.Status {
	case storage.AgentStatusRunning:
		gqlStatus = AgentStatusRunning
	case storage.AgentStatusPaused:
		gqlStatus = AgentStatusPaused
	}
	gqlMode := AgentModeNormal
	switch st.Mode {
	case storage.AgentModePlan:
		gqlMode = AgentModePlan
	case storage.AgentModeAutonomous:
		gqlMode = AgentModeAutonomous
	}
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: gqlStatus, Mode: gqlMode, PlanContent: &content,
	})
	return true, nil
}

// SaveViewState is the resolver for the saveViewState field.
func (r *mutationResolver) SaveViewState(ctx context.Context, threadID string, state ViewStateInput) (*ViewState, error) {
	data, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal view state: %w", err)
	}
	if err := r.DB.SaveViewState(threadID, data); err != nil {
		return nil, err
	}
	return &ViewState{
		ThreadID:               threadID,
		ScrollPosition:         state.ScrollPosition,
		ExpandedMessageIds:     state.ExpandedMessageIds,
		InputDraft:             state.InputDraft,
		CitationExpansionState: state.CitationExpansionState,
	}, nil
}

// Threads is the resolver for the threads field.
func (r *queryResolver) Threads(ctx context.Context, includeArchived *bool) ([]*pb.Thread, error) {
	incArch := false
	if includeArchived != nil {
		incArch = *includeArchived
	}
	pbThreads, err := r.DB.ListThreads(incArch)
	if err != nil {
		return nil, err
	}
	result := make([]*pb.Thread, len(pbThreads))
	for i, t := range pbThreads {
		result[i] = t
	}
	return result, nil
}

// Thread is the resolver for the thread field.
func (r *queryResolver) Thread(ctx context.Context, id string) (*pb.Thread, error) {
	t, err := r.DB.GetThread(id)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return t, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, limit *int) ([]*SearchResult, error) {
	if r.Searcher == nil {
		return nil, fmt.Errorf("search unavailable: embedder not configured")
	}
	lim := 10
	if limit != nil {
		lim = *limit
	}
	results, err := r.Searcher.Search(ctx, query, lim)
	if err != nil {
		return nil, err
	}
	gqlResults := make([]*SearchResult, len(results))
	for i, res := range results {
		msg, err := r.DB.GetMessage(res.MessageID)
		if err != nil {
			continue
		}
		thread, _ := r.DB.GetThread(msg.ThreadId)
		threadName := ""
		if thread != nil {
			threadName = thread.Name
		}
		gqlResults[i] = &SearchResult{
			MessageID:  res.MessageID,
			ThreadID:   msg.ThreadId,
			ThreadName: threadName,
			Snippet:    rrc.TextFromBlocks(msg.Content),
			Score:      res.Score,
		}
	}
	return gqlResults, nil
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, threadID string, limit *int, offset *int) ([]*pb.Message, error) {
	lim, off := 0, 0
	if limit != nil {
		lim = *limit
	}
	if offset != nil {
		off = *offset
	}
	msgs, err := r.DB.ListMessages(threadID, lim, off)
	if err != nil {
		return nil, err
	}
	return msgs, nil
}

// SelectionForMessage returns the SelectionResult that drove the turn
// which produced the given target message. Pure DB lookup — this is
// the primary path for auditing any historical turn, live or long past.
func (r *queryResolver) SelectionForMessage(ctx context.Context, messageID string) (*pb.SelectionResult, error) {
	return r.DB.GetSelectionForMessage(messageID)
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*Settings, error) {
	s := r.Config.Settings
	providers, err := json.Marshal(s.Providers)
	if err != nil {
		return nil, fmt.Errorf("marshal providers: %w", err)
	}
	permissions, err := json.Marshal(s.Permissions)
	if err != nil {
		return nil, fmt.Errorf("marshal permissions: %w", err)
	}
	mcpServers, err := json.Marshal(s.MCPServers)
	if err != nil {
		return nil, fmt.Errorf("marshal mcp servers: %w", err)
	}
	hooks, err := json.Marshal(s.Hooks)
	if err != nil {
		return nil, fmt.Errorf("marshal hooks: %w", err)
	}
	preferences, err := json.Marshal(s.Preferences)
	if err != nil {
		return nil, fmt.Errorf("marshal preferences: %w", err)
	}
	// Serialize engine config from the currently-live engine, not from
	// config file. This lets the UI reflect the actual operating
	// config (including any defaults that kicked in when Settings had
	// zero-value engine fields).
	engineCfg := r.Engine().Config()
	engine, err := json.Marshal(map[string]any{
		"edge_threshold":        engineCfg.EdgeThreshold,
		"score_floor":           engineCfg.ScoreFloor,
		"z_score_threshold":     engineCfg.ZScoreThreshold,
		"min_batch_stddev":      engineCfg.MinBatchStdDev,
		"radius_size":           engineCfg.RadiusSize,
		"rerank_top_k":          engineCfg.RerankTopK,
		"context_budget_tokens": engineCfg.ContextBudgetTokens,
	})
	if err != nil {
		return nil, fmt.Errorf("marshal engine config: %w", err)
	}
	return &Settings{
		Providers:   string(providers),
		Permissions: string(permissions),
		McpServers:  string(mcpServers),
		Hooks:       string(hooks),
		Preferences: string(preferences),
		Engine:      string(engine),
	}, nil
}

// ViewState is the resolver for the viewState field.
func (r *queryResolver) ViewState(ctx context.Context, threadID string) (*ViewState, error) {
	data, err := r.DB.GetViewState(threadID)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	var vs ViewState
	if err := json.Unmarshal(data, &vs); err != nil {
		return nil, fmt.Errorf("unmarshal view state: %w", err)
	}
	vs.ThreadID = threadID
	return &vs, nil
}

// AgentState is the resolver for the agentState query field.
func (r *queryResolver) AgentState(ctx context.Context, threadID string) (*AgentState, error) {
	st, err := r.DB.GetAgentState(threadID)
	if err != nil {
		return &AgentState{
			ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModeNormal,
		}, nil
	}
	status := AgentStatusIdle
	if st.Status == storage.AgentStatusRunning {
		status = AgentStatusRunning
	} else if st.Status == storage.AgentStatusPaused {
		status = AgentStatusPaused
	}
	mode := AgentModeNormal
	if st.Mode == storage.AgentModeAutonomous {
		mode = AgentModeAutonomous
	} else if st.Mode == storage.AgentModePlan {
		mode = AgentModePlan
	}
	result := &AgentState{
		ThreadID:   threadID,
		Status:     status,
		Mode:       mode,
		RoundCount: st.RoundCount,
	}
	if st.DurationLimit != "" {
		result.DurationLimit = &st.DurationLimit
	}
	if pc := r.GetPlan(threadID); pc != "" {
		result.PlanContent = &pc
	}
	return result, nil
}

// Skills is the resolver for the skills field.
func (r *queryResolver) Skills(ctx context.Context) ([]*SkillInfo, error) {
	loaded := r.Resolver.Skills
	result := make([]*SkillInfo, len(loaded))
	for i, s := range loaded {
		result[i] = &SkillInfo{Name: s.Name, Description: s.Description}
	}
	return result, nil
}

// RecentActivity is the resolver for the recentActivity field.
func (r *queryResolver) RecentActivity(ctx context.Context, limit *int) ([]*ActivityItem, error) {
	lim := 10
	if limit != nil {
		lim = *limit
	}
	var items []*ActivityItem

	// Recent threads with messages (activity = latest message per thread)
	threads, err := r.DB.ListThreads(false)
	if err != nil {
		return nil, fmt.Errorf("list threads: %w", err)
	}
	for _, t := range threads {
		lastMsg := r.DB.LatestMessage(t.Id)
		if lastMsg == nil {
			continue
		}
		summary := rrc.TextFromBlocks(lastMsg.Content)
		if len(summary) > 80 {
			summary = summary[:77] + "..."
		}
		items = append(items, &ActivityItem{
			Type:       "message",
			ThreadID:   t.Id,
			ThreadName: t.Name,
			Summary:    summary,
			Timestamp:  lastMsg.CreatedAt.AsTime(),
		})
	}

	// Recent autonomous completions
	// (agent state with status=0 and mode=0 that previously was autonomous)
	// For now, we use the thread-based activity above as the primary signal

	// Sort by timestamp descending
	for i := 1; i < len(items); i++ {
		for j := i; j > 0 && items[j].Timestamp.After(items[j-1].Timestamp); j-- {
			items[j], items[j-1] = items[j-1], items[j]
		}
	}

	if len(items) > lim {
		items = items[:lim]
	}
	return items, nil
}

// EffectiveScore is the resolver for the effectiveScore field.
func (r *selectedMessageResolver) EffectiveScore(ctx context.Context, obj *pb.SelectedMessage) (float64, error) {
	return float64(obj.EffectiveScore), nil
}

// CrossEncoderScore is the resolver for the crossEncoderScore field.
func (r *selectedMessageResolver) CrossEncoderScore(ctx context.Context, obj *pb.SelectedMessage) (float64, error) {
	if len(obj.ViaEdges) > 0 {
		return float64(obj.ViaEdges[0].CrossEncoderScore), nil
	}
	return 0, nil
}

// TemporalProximity is the resolver for the temporalProximity field.
func (r *selectedMessageResolver) TemporalProximity(ctx context.Context, obj *pb.SelectedMessage) (float64, error) {
	if len(obj.ViaEdges) > 0 {
		return float64(obj.ViaEdges[0].TemporalProximity), nil
	}
	return 0, nil
}

// Scope is the resolver for the scope field.
func (r *selectionResultResolver) Scope(ctx context.Context, obj *pb.SelectionResult) (SelectionScope, error) {
	if obj.Scope == pb.SelectionScope_SELECTION_SCOPE_ALL_THREADS {
		return SelectionScopeAllThreads, nil
	}
	return SelectionScopeThread, nil
}

// MessageStream is the resolver for the messageStream field.
func (r *subscriptionResolver) MessageStream(ctx context.Context, threadID string) (<-chan *StreamEvent, error) {
	ch := r.streams.Subscribe(threadID)
	unsubscribeOnDone(ctx, func() { r.streams.Unsubscribe(threadID, ch) })
	return ch, nil
}

// AgentState is the resolver for the agentState field.
func (r *subscriptionResolver) AgentState(ctx context.Context, threadID string) (<-chan *AgentState, error) {
	ch := r.agents.Subscribe(threadID)
	unsubscribeOnDone(ctx, func() { r.agents.Unsubscribe(threadID, ch) })
	return ch, nil
}

// ToolExecution is the resolver for the toolExecution field.
func (r *subscriptionResolver) ToolExecution(ctx context.Context, threadID string) (<-chan *ToolExecution, error) {
	ch := r.tools.Subscribe(threadID)
	unsubscribeOnDone(ctx, func() { r.tools.Unsubscribe(threadID, ch) })
	return ch, nil
}

// SubagentProgress is the resolver for the subagentProgress field.
func (r *subscriptionResolver) SubagentProgress(ctx context.Context, threadID string) (<-chan *SubagentProgress, error) {
	ch := r.subagents.Subscribe(threadID)
	unsubscribeOnDone(ctx, func() { r.subagents.Unsubscribe(threadID, ch) })
	return ch, nil
}

// ThreadStateChanges is the resolver for the threadStateChanges field.
func (r *subscriptionResolver) ThreadStateChanges(ctx context.Context) (<-chan *ThreadStateEvent, error) {
	ch := r.threads.Subscribe()
	unsubscribeOnDone(ctx, func() { r.threads.Unsubscribe(ch) })
	return ch, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *threadResolver) CreatedAt(ctx context.Context, obj *pb.Thread) (*time.Time, error) {
	if obj.CreatedAt != nil {
		t := obj.CreatedAt.AsTime()
		return &t, nil
	}
	return nil, nil
}

// ArchivedAt is the resolver for the archivedAt field.
func (r *threadResolver) ArchivedAt(ctx context.Context, obj *pb.Thread) (*time.Time, error) {
	if obj.ArchivedAt != nil {
		t := obj.ArchivedAt.AsTime()
		return &t, nil
	}
	return nil, nil
}

// MessageCount is the resolver for the messageCount field.
func (r *threadResolver) MessageCount(ctx context.Context, obj *pb.Thread) (int, error) {
	return r.DB.MessageCount(obj.Id), nil
}

// Status resolves the live agent status for a thread from
// agent_state. Threads with no row default to Idle so a brand-new
// thread reads cleanly without an explicit status insert.
func (r *threadResolver) Status(ctx context.Context, obj *pb.Thread) (AgentStatus, error) {
	st, _ := r.DB.GetAgentState(obj.Id)
	if st == nil {
		return AgentStatusIdle, nil
	}
	switch st.Status {
	case storage.AgentStatusRunning:
		return AgentStatusRunning, nil
	case storage.AgentStatusPaused:
		return AgentStatusPaused, nil
	default:
		return AgentStatusIdle, nil
	}
}

// Mode resolves the live agent mode for a thread from agent_state.
// Defaults to Normal when no row exists.
func (r *threadResolver) Mode(ctx context.Context, obj *pb.Thread) (AgentMode, error) {
	st, _ := r.DB.GetAgentState(obj.Id)
	if st == nil {
		return AgentModeNormal, nil
	}
	switch st.Mode {
	case storage.AgentModeAutonomous:
		return AgentModeAutonomous, nil
	case storage.AgentModePlan:
		return AgentModePlan, nil
	default:
		return AgentModeNormal, nil
	}
}

// Edge returns EdgeResolver implementation.
func (r *Resolver) Edge() EdgeResolver { return &edgeResolver{r} }

// ExcludedMessage returns ExcludedMessageResolver implementation.
func (r *Resolver) ExcludedMessage() ExcludedMessageResolver { return &excludedMessageResolver{r} }

// Message returns MessageResolver implementation.
func (r *Resolver) Message() MessageResolver { return &messageResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SelectedMessage returns SelectedMessageResolver implementation.
func (r *Resolver) SelectedMessage() SelectedMessageResolver { return &selectedMessageResolver{r} }

// SelectionResult returns SelectionResultResolver implementation.
func (r *Resolver) SelectionResult() SelectionResultResolver { return &selectionResultResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Thread returns ThreadResolver implementation.
func (r *Resolver) Thread() ThreadResolver { return &threadResolver{r} }

type edgeResolver struct{ *Resolver }
type excludedMessageResolver struct{ *Resolver }
type messageResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type selectedMessageResolver struct{ *Resolver }
type selectionResultResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type threadResolver struct{ *Resolver }
