package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/emontenegr/grudge/proto/gen/go/grudge/v1"
	"github.com/emontenegr/grudge/rrc"
	"github.com/emontenegr/grudge/service/storage"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// CreateThread is the resolver for the createThread field.
func (r *mutationResolver) CreateThread(ctx context.Context, name *string, workingDirs []string, sandboxed *bool) (*v1.Thread, error) {
	threadName := ""
	if name != nil {
		threadName = *name
	}
	// Auto-set working directory to CWD if none provided
	if len(workingDirs) == 0 {
		if cwd, err := os.Getwd(); err == nil {
			workingDirs = []string{cwd}
		}
	}
	// Default to sandboxed=true when unset: Bash + file tools are
	// confined to a per-thread workspace via sandbox.WorkspaceDir.
	// Protects the host from prompt-injected commands that would
	// otherwise read keys / overwrite arbitrary files. Callers can
	// pass sandboxed=false at creation for threads that genuinely
	// need host access.
	sbx := true
	if sandboxed != nil {
		sbx = *sandboxed
	}
	t := &v1.Thread{
		Id:          fmt.Sprintf("thread-%d", time.Now().UnixNano()),
		Name:        threadName,
		WorkingDirs: workingDirs,
		Sandboxed:   sbx,
		CreatedAt:   timestamppb.Now(),
	}
	if err := r.db.CreateThread(t); err != nil {
		return nil, err
	}
	r.publishThreadState(&ThreadStateEvent{ThreadID: t.Id, Name: t.Name, Status: AgentStatusIdle, Mode: AgentModeNormal})
	return t, nil
}

// UpdateThread is the resolver for the updateThread field.
func (r *mutationResolver) UpdateThread(ctx context.Context, id string, name *string, workingDirs []string, sandboxed *bool) (*v1.Thread, error) {
	t, err := r.db.GetThread(id)
	if err != nil {
		return nil, err
	}
	if name != nil {
		t.Name = *name
	}
	if workingDirs != nil {
		t.WorkingDirs = workingDirs
	}
	if sandboxed != nil {
		t.Sandboxed = *sandboxed
	}
	if err := r.db.UpdateThread(t); err != nil {
		return nil, err
	}
	return t, nil
}

// DeleteThread is the resolver for the deleteThread field.
func (r *mutationResolver) DeleteThread(ctx context.Context, id string) (bool, error) {
	if err := r.db.DeleteThread(id); err != nil {
		return false, err
	}
	r.db.DeleteEdgesForThread(id)
	r.publishThreadState(&ThreadStateEvent{ThreadID: id})
	return true, nil
}

// ArchiveThread is the resolver for the archiveThread field.
func (r *mutationResolver) ArchiveThread(ctx context.Context, id string) (bool, error) {
	if err := r.db.ArchiveThread(id); err != nil {
		return false, err
	}
	r.publishThreadState(&ThreadStateEvent{ThreadID: id})
	return true, nil
}

// UnarchiveThread is the resolver for the unarchiveThread field.
func (r *mutationResolver) UnarchiveThread(ctx context.Context, id string) (bool, error) {
	if err := r.db.UnarchiveThread(id); err != nil {
		return false, err
	}
	r.publishThreadState(&ThreadStateEvent{ThreadID: id})
	return true, nil
}

// SaveViewState is the resolver for the saveViewState field.
func (r *mutationResolver) SaveViewState(ctx context.Context, threadID string, state ViewStateInput) (*ViewState, error) {
	data, err := json.Marshal(state)
	if err != nil {
		return nil, fmt.Errorf("marshal view state: %w", err)
	}
	if err := r.db.SaveViewState(threadID, data); err != nil {
		return nil, err
	}
	return &ViewState{
		ThreadID:               threadID,
		ScrollPosition:         state.ScrollPosition,
		ExpandedMessageIds:     state.ExpandedMessageIds,
		InputDraft:             state.InputDraft,
		CitationExpansionState: state.CitationExpansionState,
	}, nil
}

// Threads is the resolver for the threads field.
func (r *queryResolver) Threads(ctx context.Context, includeArchived *bool) ([]*v1.Thread, error) {
	incArch := false
	if includeArchived != nil {
		incArch = *includeArchived
	}
	pbThreads, err := r.db.ListThreads(incArch)
	if err != nil {
		return nil, err
	}
	result := make([]*v1.Thread, len(pbThreads))
	for i, t := range pbThreads {
		result[i] = t
	}
	return result, nil
}

// Thread is the resolver for the thread field.
func (r *queryResolver) Thread(ctx context.Context, id string) (*v1.Thread, error) {
	t, err := r.db.GetThread(id)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return t, nil
}

// ViewState is the resolver for the viewState field.
func (r *queryResolver) ViewState(ctx context.Context, threadID string) (*ViewState, error) {
	data, err := r.db.GetViewState(threadID)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	var vs ViewState
	if err := json.Unmarshal(data, &vs); err != nil {
		return nil, fmt.Errorf("unmarshal view state: %w", err)
	}
	vs.ThreadID = threadID
	return &vs, nil
}

// RecentActivity is the resolver for the recentActivity field.
func (r *queryResolver) RecentActivity(ctx context.Context, limit *int) ([]*ActivityItem, error) {
	lim := 10
	if limit != nil {
		lim = *limit
	}
	var items []*ActivityItem

	// Recent threads with messages (activity = latest message per thread)
	threads, err := r.db.ListThreads(false)
	if err != nil {
		return nil, fmt.Errorf("list threads: %w", err)
	}
	for _, t := range threads {
		lastMsg := r.db.LatestMessage(t.Id)
		if lastMsg == nil {
			continue
		}
		summary := rrc.TextFromBlocks(lastMsg.Content)
		if len(summary) > 80 {
			summary = summary[:77] + "..."
		}
		items = append(items, &ActivityItem{
			Type:       "message",
			ThreadID:   t.Id,
			ThreadName: t.Name,
			Summary:    summary,
			Timestamp:  lastMsg.CreatedAt.AsTime(),
		})
	}

	// Recent autonomous completions
	// (agent state with status=0 and mode=0 that previously was autonomous)
	// For now, we use the thread-based activity above as the primary signal

	// Sort by timestamp descending
	for i := 1; i < len(items); i++ {
		for j := i; j > 0 && items[j].Timestamp.After(items[j-1].Timestamp); j-- {
			items[j], items[j-1] = items[j-1], items[j]
		}
	}

	if len(items) > lim {
		items = items[:lim]
	}
	return items, nil
}

// ThreadStateChanges is the resolver for the threadStateChanges field.
func (r *subscriptionResolver) ThreadStateChanges(ctx context.Context) (<-chan *ThreadStateEvent, error) {
	ch := r.threads.Subscribe()
	unsubscribeOnDone(ctx, func() { r.threads.Unsubscribe(ch) })
	return ch, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *threadResolver) CreatedAt(ctx context.Context, obj *v1.Thread) (*time.Time, error) {
	if obj.CreatedAt != nil {
		t := obj.CreatedAt.AsTime()
		return &t, nil
	}
	return nil, nil
}

// ArchivedAt is the resolver for the archivedAt field.
func (r *threadResolver) ArchivedAt(ctx context.Context, obj *v1.Thread) (*time.Time, error) {
	if obj.ArchivedAt != nil {
		t := obj.ArchivedAt.AsTime()
		return &t, nil
	}
	return nil, nil
}

// MessageCount is the resolver for the messageCount field.
func (r *threadResolver) MessageCount(ctx context.Context, obj *v1.Thread) (int, error) {
	return r.db.MessageCount(obj.Id), nil
}

// Status resolves the live agent status for a thread from
// agent_state. Threads with no row default to Idle so a brand-new
// thread reads cleanly without an explicit status insert.
func (r *threadResolver) Status(ctx context.Context, obj *v1.Thread) (AgentStatus, error) {
	st, _ := r.db.GetAgentState(obj.Id)
	if st == nil {
		return AgentStatusIdle, nil
	}
	switch st.Status {
	case storage.AgentStatusRunning:
		return AgentStatusRunning, nil
	case storage.AgentStatusPaused:
		return AgentStatusPaused, nil
	default:
		return AgentStatusIdle, nil
	}
}

// Mode resolves the live agent mode for a thread from agent_state.
// Defaults to Normal when no row exists.
func (r *threadResolver) Mode(ctx context.Context, obj *v1.Thread) (AgentMode, error) {
	st, _ := r.db.GetAgentState(obj.Id)
	if st == nil {
		return AgentModeNormal, nil
	}
	switch st.Mode {
	case storage.AgentModeAutonomous:
		return AgentModeAutonomous, nil
	case storage.AgentModePlan:
		return AgentModePlan, nil
	default:
		return AgentModeNormal, nil
	}
}

// Thread returns ThreadResolver implementation.
func (r *Resolver) Thread() ThreadResolver { return &threadResolver{r} }

type threadResolver struct{ *Resolver }
