package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"time"

	"github.com/elijahmontenegro/grudge/proto/gen/go/grudge/v1"
	"github.com/elijahmontenegro/grudge/rrc"
	"github.com/elijahmontenegro/grudge/service/storage"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// StopAgent is the resolver for the stopAgent field.
func (r *mutationResolver) StopAgent(ctx context.Context, threadID string) (bool, error) {
	r.stopRunner(threadID)
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModeNormal,
	})
	if err := r.db.EnsureAgentStateRow(threadID, storage.AgentStatusIdle, storage.AgentModeNormal); err != nil {
		return false, err
	}
	return true, r.db.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModeNormal)
}

// PauseAgent is the resolver for the pauseAgent field.
func (r *mutationResolver) PauseAgent(ctx context.Context, threadID string) (bool, error) {
	if entry, ok := r.runners.Get(threadID); ok {
		entry.Runner.PauseAutonomous()
	}
	st, err := r.db.GetAgentState(threadID)
	if err != nil {
		return false, fmt.Errorf("load state: %w", err)
	}
	gqlMode := AgentModeNormal
	switch st.Mode {
	case storage.AgentModePlan:
		gqlMode = AgentModePlan
	case storage.AgentModeAutonomous:
		gqlMode = AgentModeAutonomous
	}
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusPaused, Mode: gqlMode,
	})
	return true, r.db.SetAgentStatus(threadID, storage.AgentStatusPaused)
}

// ResumeAgent is the resolver for the resumeAgent field.
func (r *mutationResolver) ResumeAgent(ctx context.Context, threadID string, correction *string) (bool, error) {
	if correction != nil && *correction != "" {
		corpus, err := r.db.ThreadCorpus(threadID)
		if err != nil {
			return false, fmt.Errorf("load corpus: %w", err)
		}
		msg := &v1.Message{
			Id:        fmt.Sprintf("msg-%d", time.Now().UnixNano()),
			Role:      v1.Role_ROLE_USER,
			Content:   rrc.BlocksFromText(*correction),
			Position:  int64(len(corpus)),
			ThreadId:  threadID,
			CreatedAt: timestamppb.Now(),
		}
		if err := r.storeMessage(msg, *correction); err != nil {
			return false, fmt.Errorf("insert correction: %w", err)
		}
	}
	// Same full-row UPSERT concern as PauseAgent — preserve Mode/RoundCount
	// rather than zeroing them via a partial state save.
	st, err := r.db.GetAgentState(threadID)
	if err != nil {
		return false, fmt.Errorf("load state: %w", err)
	}
	// Two resume paths:
	//   (a) Active autonomous loop, just paused → flip the pause gate.
	//   (b) Dead autonomous loop (runner exited, e.g. ctx cancel) but DB
	//       still has Mode=Autonomous → kick a fresh RunAutonomous
	//       goroutine so the UX doesn't lie.
	entry, haveEntry := r.runners.Get(threadID)
	if haveEntry && entry.Runner.IsAutonomousActive() {
		entry.Runner.ResumeAutonomous()
	} else if st.Mode == storage.AgentModeAutonomous {
		remaining, reason := st.RemainingBudget()
		if reason == "" && remaining > 0 {
			runner, rerr := r.getOrCreateRunner(threadID)
			if rerr != nil {
				return false, fmt.Errorf("restart runner: %w", rerr)
			}
			autoCtx, autoCancel := context.WithCancel(context.Background())
			r.runners.SetCancel(threadID, autoCancel)
			// Continuation prompt — non-empty so the model gets a
			// clear directive rather than inferring from RRC alone.
			// If the caller supplied a correction it's already been
			// stored above; the "continue" kickoff still picks it up
			// via Selection on the first round.
			kickoff := "continue"
			if correction != nil && *correction != "" {
				kickoff = *correction
			}
			go func() {
				defer r.stopRunner(threadID)
				defer r.db.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModeNormal)
				defer r.publishAgentState(threadID, &AgentState{ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModeNormal})
				if err := runner.RunAutonomous(autoCtx, kickoff, remaining); err != nil {
					log.Printf("[Autonomous resumed] Error: %v", err)
				}
			}()
		}
	}
	gqlMode := AgentModeNormal
	switch st.Mode {
	case storage.AgentModePlan:
		gqlMode = AgentModePlan
	case storage.AgentModeAutonomous:
		gqlMode = AgentModeAutonomous
	}
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusRunning, Mode: gqlMode,
	})
	return true, r.db.SetAgentStatus(threadID, storage.AgentStatusRunning)
}

// StartAutonomous is the resolver for the startAutonomous field.
func (r *mutationResolver) StartAutonomous(ctx context.Context, threadID string, prompt string, duration string, attachments []*AttachmentInput) (bool, error) {
	dur, err := time.ParseDuration(duration)
	if err != nil {
		return false, fmt.Errorf("invalid duration: %w", err)
	}
	const minDur = 5 * time.Minute
	const maxDur = 14 * 24 * time.Hour
	if dur < minDur {
		return false, fmt.Errorf("minimum autonomous duration is 5m")
	}
	if dur > maxDur {
		dur = maxDur
	}
	now := time.Now()
	if err := r.db.StartAutonomousRun(threadID, now, duration); err != nil {
		return false, err
	}

	// Launch the autonomous loop in a goroutine
	runner, err := r.getOrCreateRunner(threadID)
	if err != nil {
		return false, fmt.Errorf("create runner: %w", err)
	}
	autoCtx, autoCancel := context.WithCancel(context.Background())
	r.runners.SetCancel(threadID, autoCancel)

	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusRunning, Mode: AgentModeAutonomous,
		RoundCount: 0, DurationLimit: &duration,
	})

	go func() {
		defer r.stopRunner(threadID)
		defer r.db.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModeNormal)
		defer r.publishAgentState(threadID, &AgentState{
			ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModeNormal,
		})
		if err := runner.RunAutonomous(autoCtx, prompt, dur, attachmentInputsToBlocks(attachments)...); err != nil {
			log.Printf("[Autonomous] Error: %v", err)
		}
	}()

	return true, nil
}

// EnterPlanMode is the resolver for the enterPlanMode field.
// Plan mode is a permission/intent state, NOT an execution status — flipping
// the composer pill to "plan" without sending anything must not make the UI
// claim "agent is running." Keep Status=Idle; Mode=Plan. The runner still
// gets restarted so the plan-mode system prompt is reassembled for the next
// SendMessage. Mirrors claude-code's model where plan mode is a
// toolPermissionContext.mode flag, not an agent status.
func (r *mutationResolver) EnterPlanMode(ctx context.Context, threadID string) (bool, error) {
	if err := r.db.EnsureAgentStateRow(threadID, storage.AgentStatusIdle, storage.AgentModePlan); err != nil {
		return false, err
	}
	if err := r.db.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModePlan); err != nil {
		return false, err
	}
	// Stop existing runner so a fresh one is created with plan mode prompt
	r.stopRunner(threadID)
	// Creating the runner now picks up mode=plan from DB, assembles plan mode system prompt
	if _, err := r.getOrCreateRunner(threadID); err != nil {
		return false, fmt.Errorf("create runner: %w", err)
	}
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModePlan,
	})
	return true, nil
}

// ApprovePlan is the resolver for the approvePlan field.
// For Manual mode: clears plan content + flips mode to Normal. Status stays
// Idle since nothing is actively running — the model will implement on the
// user's next message (or they can ask for specific changes). Publishing
// Running here would phantom-signal activity just like round-120's
// EnterPlanMode bug.
// For Autonomous mode: same state changes, plus kicks a RunAutonomous
// goroutine with an "implement the plan" prompt. Status=Running there
// because the goroutine actually runs.
func (r *mutationResolver) ApprovePlan(ctx context.Context, threadID string, executionMode ExecutionMode) (bool, error) {
	stMode := storage.AgentModeNormal
	gqlMode := AgentModeNormal
	if executionMode == ExecutionModeAutonomous {
		stMode = storage.AgentModeAutonomous
		gqlMode = AgentModeAutonomous
	}
	// Manual: Idle (nothing running). Autonomous: Running (goroutine below).
	stStatus := storage.AgentStatusIdle
	gqlStatus := AgentStatusIdle
	if executionMode == ExecutionModeAutonomous {
		stStatus = storage.AgentStatusRunning
		gqlStatus = AgentStatusRunning
	}
	if err := r.db.EnsureAgentStateRow(threadID, stStatus, stMode); err != nil {
		return false, err
	}
	if err := r.db.SetAgentStatusAndMode(threadID, stStatus, stMode); err != nil {
		return false, err
	}
	// Clear plan content — it's been approved and enters the corpus
	r.plans.Clear(threadID)
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: gqlStatus, Mode: gqlMode,
	})

	if executionMode == ExecutionModeAutonomous {
		// Kick an autonomous loop so "approve · autonomous" actually does
		// something. Default duration 1h — the PlanPanel's autonomous
		// approve button doesn't currently pass a duration; we use a sane
		// default and let the user stop/extend via the topbar controls.
		const defaultDuration = "1h"
		dur, _ := time.ParseDuration(defaultDuration)
		runner, err := r.getOrCreateRunner(threadID)
		if err != nil {
			return false, fmt.Errorf("create runner: %w", err)
		}
		autoCtx, autoCancel := context.WithCancel(context.Background())
		r.runners.SetCancel(threadID, autoCancel)
		go func() {
			defer r.stopRunner(threadID)
			defer r.db.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModeNormal)
			defer r.publishAgentState(threadID, &AgentState{
				ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModeNormal,
			})
			// Non-empty prompt so the model gets a concrete directive — an
			// empty-content user turn would leave it inferring from RRC
			// selection alone, which is less reliable for a post-approval
			// handoff. The model already has the approved plan in context
			// (ExitPlan tool_result + plan.adoc on disk), but naming the
			// transition explicitly is cheap and unambiguous.
			const approvedPrompt = "Plan approved. Proceed with implementation. Re-read plan.adoc if any detail is unclear."
			if err := runner.RunAutonomous(autoCtx, approvedPrompt, dur); err != nil {
				log.Printf("[Autonomous plan-approved] Error: %v", err)
			}
		}()
	}
	return true, nil
}

// RejectPlan is the resolver for the rejectPlan field.
// Clears stored plan content, re-enters plan mode with a fresh runner so the
// plan-mode system prompt is re-applied, and publishes cleared agent state
// so the PlanPanel closes. The caller is expected to follow up with a
// sendMessage carrying the feedback so the model revises plan.adoc.
func (r *mutationResolver) RejectPlan(ctx context.Context, threadID string, feedback *string) (bool, error) {
	r.plans.Clear(threadID)

	// Status stays Idle — rejectPlan itself doesn't execute a round. The
	// follow-up sendMessage carrying the feedback is what actually kicks
	// the revision round; its streaming surfaces via the usual path.
	if err := r.db.EnsureAgentStateRow(threadID, storage.AgentStatusIdle, storage.AgentModePlan); err != nil {
		return false, err
	}
	if err := r.db.SetAgentStatusAndMode(threadID, storage.AgentStatusIdle, storage.AgentModePlan); err != nil {
		return false, err
	}
	// Stop the current runner so the next getOrCreateRunner picks up plan
	// mode and rebuilds the system prompt from scratch (no stale plan in it).
	r.stopRunner(threadID)
	if _, err := r.getOrCreateRunner(threadID); err != nil {
		return false, fmt.Errorf("create runner: %w", err)
	}
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModePlan,
		PlanContent: nil,
	})
	_ = feedback // reserved for future inline-feedback injection; caller currently sends feedback via sendMessage
	return true, nil
}

// UpdatePlanSource is the resolver for the updatePlanSource field.
// Overwrites plan.adoc with user-edited content before approval. Updates the
// in-memory plan-content cache and re-publishes agentState so the PlanPanel
// re-renders with the edited version. The model will see the new content on
// its next FileRead of plan.adoc.
func (r *mutationResolver) UpdatePlanSource(ctx context.Context, threadID string, content string) (bool, error) {
	planDir, err := storage.PlanDirForThread(r.cfg.DataDir, threadID)
	if err != nil {
		return false, err
	}
	planPath := filepath.Join(planDir, "plan.adoc")
	if err := os.MkdirAll(planDir, 0o755); err != nil {
		return false, fmt.Errorf("ensure plan dir: %w", err)
	}
	if err := os.WriteFile(planPath, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("write plan: %w", err)
	}
	r.plans.Set(threadID, content)

	// Re-publish agentState with the fresh plan content. Preserve whatever
	// status/mode the runner is currently reporting — editing the plan is
	// an out-of-band user action, not a state transition.
	st, err := r.db.GetAgentState(threadID)
	if err != nil {
		// State missing is non-fatal here — the file write already succeeded
		// and a subsequent approve/reject will re-publish with sane defaults.
		return true, nil
	}
	gqlStatus := AgentStatusIdle
	switch st.Status {
	case storage.AgentStatusRunning:
		gqlStatus = AgentStatusRunning
	case storage.AgentStatusPaused:
		gqlStatus = AgentStatusPaused
	}
	gqlMode := AgentModeNormal
	switch st.Mode {
	case storage.AgentModePlan:
		gqlMode = AgentModePlan
	case storage.AgentModeAutonomous:
		gqlMode = AgentModeAutonomous
	}
	r.publishAgentState(threadID, &AgentState{
		ThreadID: threadID, Status: gqlStatus, Mode: gqlMode, PlanContent: &content,
	})
	return true, nil
}

// AgentState is the resolver for the agentState query field.
func (r *queryResolver) AgentState(ctx context.Context, threadID string) (*AgentState, error) {
	st, err := r.db.GetAgentState(threadID)
	if err != nil {
		return &AgentState{
			ThreadID: threadID, Status: AgentStatusIdle, Mode: AgentModeNormal,
		}, nil
	}
	status := AgentStatusIdle
	if st.Status == storage.AgentStatusRunning {
		status = AgentStatusRunning
	} else if st.Status == storage.AgentStatusPaused {
		status = AgentStatusPaused
	}
	mode := AgentModeNormal
	if st.Mode == storage.AgentModeAutonomous {
		mode = AgentModeAutonomous
	} else if st.Mode == storage.AgentModePlan {
		mode = AgentModePlan
	}
	result := &AgentState{
		ThreadID:   threadID,
		Status:     status,
		Mode:       mode,
		RoundCount: st.RoundCount,
	}
	if st.DurationLimit != "" {
		result.DurationLimit = &st.DurationLimit
	}
	if pc := r.plans.Get(threadID); pc != "" {
		result.PlanContent = &pc
	}
	return result, nil
}

// AgentState is the resolver for the agentState field.
func (r *subscriptionResolver) AgentState(ctx context.Context, threadID string) (<-chan *AgentState, error) {
	ch := r.agents.Subscribe(threadID)
	unsubscribeOnDone(ctx, func() { r.agents.Unsubscribe(threadID, ch) })
	return ch, nil
}
