package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/elijahmontenegro/grudge/proto/gen/go/grudge/v1"
	"github.com/elijahmontenegro/grudge/rrc"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// ApproveToolCall is the resolver for the approveToolCall field.
func (r *mutationResolver) ApproveToolCall(ctx context.Context, callID string) (bool, error) {
	if !r.approvals.SendApproval(callID, true) {
		return false, fmt.Errorf("no pending approval for call %s", callID)
	}
	return true, nil
}

// DenyToolCall is the resolver for the denyToolCall field.
func (r *mutationResolver) DenyToolCall(ctx context.Context, callID string, reason *string) (bool, error) {
	threadID := r.approvals.ThreadIDForCall(callID)
	// Inject denial feedback as a system message — the user's denial reason is
	// operational context for the model, not a user utterance. It belongs in the
	// system domain, not the conversation.
	if reason != nil && *reason != "" && threadID != "" {
		corpus, _ := r.db.ThreadCorpus(threadID)
		denialText := fmt.Sprintf("Tool call denied by user. Reason: %s", *reason)
		msg := &v1.Message{
			Id:        fmt.Sprintf("msg-%d", time.Now().UnixNano()),
			Role:      v1.Role_ROLE_SYSTEM,
			Content:   rrc.BlocksFromText(denialText),
			Position:  int64(len(corpus)),
			ThreadId:  threadID,
			CreatedAt: timestamppb.Now(),
		}
		_ = r.storeMessage(msg, denialText)
	}
	if !r.approvals.SendApproval(callID, false) {
		return false, fmt.Errorf("no pending approval for call %s", callID)
	}
	return true, nil
}

// AnswerQuestion is the resolver for the answerQuestion field.
func (r *mutationResolver) AnswerQuestion(ctx context.Context, callID string, answer string) (bool, error) {
	if !r.approvals.SendAnswer(callID, answer) {
		return false, fmt.Errorf("no pending question for call %s", callID)
	}
	return true, nil
}

// ToolExecution is the resolver for the toolExecution field.
func (r *subscriptionResolver) ToolExecution(ctx context.Context, threadID string) (<-chan *ToolExecution, error) {
	ch := r.tools.Subscribe(threadID)
	unsubscribeOnDone(ctx, func() { r.tools.Unsubscribe(threadID, ch) })
	return ch, nil
}

// SubagentProgress is the resolver for the subagentProgress field.
func (r *subscriptionResolver) SubagentProgress(ctx context.Context, threadID string) (<-chan *SubagentProgress, error) {
	ch := r.subagents.Subscribe(threadID)
	unsubscribeOnDone(ctx, func() { r.subagents.Unsubscribe(threadID, ch) })
	return ch, nil
}
