package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
)

// CreateThread is the resolver for the createThread field.
func (r *mutationResolver) CreateThread(ctx context.Context, name *string, workingDirs []string) (*Thread, error) {
	panic(fmt.Errorf("not implemented: CreateThread - createThread"))
}

// UpdateThread is the resolver for the updateThread field.
func (r *mutationResolver) UpdateThread(ctx context.Context, id string, name *string, workingDirs []string, sandboxed *bool) (*Thread, error) {
	panic(fmt.Errorf("not implemented: UpdateThread - updateThread"))
}

// DeleteThread is the resolver for the deleteThread field.
func (r *mutationResolver) DeleteThread(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteThread - deleteThread"))
}

// ArchiveThread is the resolver for the archiveThread field.
func (r *mutationResolver) ArchiveThread(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: ArchiveThread - archiveThread"))
}

// UnarchiveThread is the resolver for the unarchiveThread field.
func (r *mutationResolver) UnarchiveThread(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: UnarchiveThread - unarchiveThread"))
}

// EditMessage is the resolver for the editMessage field.
func (r *mutationResolver) EditMessage(ctx context.Context, threadID string, messagePosition int, newContent string) (*Thread, error) {
	panic(fmt.Errorf("not implemented: EditMessage - editMessage"))
}

// CompileAdoc is the resolver for the compileAdoc field.
func (r *mutationResolver) CompileAdoc(ctx context.Context, path string) (string, error) {
	panic(fmt.Errorf("not implemented: CompileAdoc - compileAdoc"))
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, threadID string, content string, scope *SelectionScope) (*Message, error) {
	panic(fmt.Errorf("not implemented: SendMessage - sendMessage"))
}

// StopAgent is the resolver for the stopAgent field.
func (r *mutationResolver) StopAgent(ctx context.Context, threadID string) (bool, error) {
	panic(fmt.Errorf("not implemented: StopAgent - stopAgent"))
}

// PauseAgent is the resolver for the pauseAgent field.
func (r *mutationResolver) PauseAgent(ctx context.Context, threadID string) (bool, error) {
	panic(fmt.Errorf("not implemented: PauseAgent - pauseAgent"))
}

// ResumeAgent is the resolver for the resumeAgent field.
func (r *mutationResolver) ResumeAgent(ctx context.Context, threadID string, correction *string) (bool, error) {
	panic(fmt.Errorf("not implemented: ResumeAgent - resumeAgent"))
}

// StartAutonomous is the resolver for the startAutonomous field.
func (r *mutationResolver) StartAutonomous(ctx context.Context, threadID string, prompt string, duration string) (bool, error) {
	panic(fmt.Errorf("not implemented: StartAutonomous - startAutonomous"))
}

// ApproveToolCall is the resolver for the approveToolCall field.
func (r *mutationResolver) ApproveToolCall(ctx context.Context, callID string) (bool, error) {
	panic(fmt.Errorf("not implemented: ApproveToolCall - approveToolCall"))
}

// DenyToolCall is the resolver for the denyToolCall field.
func (r *mutationResolver) DenyToolCall(ctx context.Context, callID string, reason *string) (bool, error) {
	panic(fmt.Errorf("not implemented: DenyToolCall - denyToolCall"))
}

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input SettingsInput) (*Settings, error) {
	panic(fmt.Errorf("not implemented: UpdateSettings - updateSettings"))
}

// EnterPlanMode is the resolver for the enterPlanMode field.
func (r *mutationResolver) EnterPlanMode(ctx context.Context, threadID string) (bool, error) {
	panic(fmt.Errorf("not implemented: EnterPlanMode - enterPlanMode"))
}

// ApprovePlan is the resolver for the approvePlan field.
func (r *mutationResolver) ApprovePlan(ctx context.Context, threadID string, executionMode ExecutionMode) (bool, error) {
	panic(fmt.Errorf("not implemented: ApprovePlan - approvePlan"))
}

// SaveViewState is the resolver for the saveViewState field.
func (r *mutationResolver) SaveViewState(ctx context.Context, threadID string, state ViewStateInput) (*ViewState, error) {
	panic(fmt.Errorf("not implemented: SaveViewState - saveViewState"))
}

// Threads is the resolver for the threads field.
func (r *queryResolver) Threads(ctx context.Context, includeArchived *bool) ([]*Thread, error) {
	panic(fmt.Errorf("not implemented: Threads - threads"))
}

// Thread is the resolver for the thread field.
func (r *queryResolver) Thread(ctx context.Context, id string) (*Thread, error) {
	panic(fmt.Errorf("not implemented: Thread - thread"))
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, limit *int) ([]*SearchResult, error) {
	panic(fmt.Errorf("not implemented: Search - search"))
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, threadID string, limit *int, offset *int) ([]*Message, error) {
	panic(fmt.Errorf("not implemented: Messages - messages"))
}

// SelectionResult is the resolver for the selectionResult field.
func (r *queryResolver) SelectionResult(ctx context.Context, eventID string) (*SelectionResult, error) {
	panic(fmt.Errorf("not implemented: SelectionResult - selectionResult"))
}

// QudGraph is the resolver for the qudGraph field.
func (r *queryResolver) QudGraph(ctx context.Context, threadID string) (*QUDGraph, error) {
	panic(fmt.Errorf("not implemented: QudGraph - qudGraph"))
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*Settings, error) {
	panic(fmt.Errorf("not implemented: Settings - settings"))
}

// ViewState is the resolver for the viewState field.
func (r *queryResolver) ViewState(ctx context.Context, threadID string) (*ViewState, error) {
	panic(fmt.Errorf("not implemented: ViewState - viewState"))
}

// Scope is the resolver for the scope field.
func (r *selectionResultResolver) Scope(ctx context.Context, obj *SelectionResult) (SelectionScope, error) {
	panic(fmt.Errorf("not implemented: Scope - scope"))
}

// MessageStream is the resolver for the messageStream field.
func (r *subscriptionResolver) MessageStream(ctx context.Context, threadID string) (<-chan *StreamEvent, error) {
	panic(fmt.Errorf("not implemented: MessageStream - messageStream"))
}

// AgentState is the resolver for the agentState field.
func (r *subscriptionResolver) AgentState(ctx context.Context, threadID string) (<-chan *AgentState, error) {
	panic(fmt.Errorf("not implemented: AgentState - agentState"))
}

// ToolExecution is the resolver for the toolExecution field.
func (r *subscriptionResolver) ToolExecution(ctx context.Context, threadID string) (<-chan *ToolExecution, error) {
	panic(fmt.Errorf("not implemented: ToolExecution - toolExecution"))
}

// SubagentProgress is the resolver for the subagentProgress field.
func (r *subscriptionResolver) SubagentProgress(ctx context.Context, threadID string) (<-chan *SubagentProgress, error) {
	panic(fmt.Errorf("not implemented: SubagentProgress - subagentProgress"))
}

// ThreadStateChanges is the resolver for the threadStateChanges field.
func (r *subscriptionResolver) ThreadStateChanges(ctx context.Context) (<-chan *ThreadStateEvent, error) {
	panic(fmt.Errorf("not implemented: ThreadStateChanges - threadStateChanges"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SelectionResult returns SelectionResultResolver implementation.
func (r *Resolver) SelectionResult() SelectionResultResolver { return &selectionResultResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type selectionResultResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
