package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log"

	"github.com/elijahmontenegro/grudge/service/config"
)

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input SettingsInput) (*Settings, error) {
	s := &r.cfg.Settings
	if input.Providers != nil {
		// Replace semantics, not merge. `json.Unmarshal` into an
		// existing map preserves keys the new payload omits; that
		// meant removing a provider in the UI never actually removed
		// it from disk. Zero the map first so the input is the
		// authoritative state.
		var next map[string]config.ProviderConfig
		if err := json.Unmarshal([]byte(*input.Providers), &next); err != nil {
			return nil, fmt.Errorf("invalid providers JSON: %w", err)
		}
		s.Providers = next
	}
	if input.Permissions != nil {
		if err := json.Unmarshal([]byte(*input.Permissions), &s.Permissions); err != nil {
			return nil, fmt.Errorf("invalid permissions JSON: %w", err)
		}
	}
	if input.McpServers != nil {
		if err := json.Unmarshal([]byte(*input.McpServers), &s.MCPServers); err != nil {
			return nil, fmt.Errorf("invalid MCP servers JSON: %w", err)
		}
	}
	if input.Hooks != nil {
		if err := json.Unmarshal([]byte(*input.Hooks), &s.Hooks); err != nil {
			return nil, fmt.Errorf("invalid hooks JSON: %w", err)
		}
	}
	if input.Preferences != nil {
		if err := json.Unmarshal([]byte(*input.Preferences), &s.Preferences); err != nil {
			return nil, fmt.Errorf("invalid preferences JSON: %w", err)
		}
	}
	if input.Engine != nil {
		var cfg config.EngineConfig
		decoder := json.NewDecoder(bytes.NewReader([]byte(*input.Engine)))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&cfg); err != nil {
			return nil, fmt.Errorf("invalid engine JSON: %w", err)
		}
		if err := cfg.Validate(); err != nil {
			return nil, err
		}
		s.Engine = cfg
		// Apply the complete snapshot onto the live engine config.
		live := cfg.ApplyTo(r.substrate.Engine().Config())
		if err := r.substrate.UpdateEngineConfig(ctx, live); err != nil {
			return nil, fmt.Errorf("update engine config: %w", err)
		}
		log.Printf("[Settings] Engine config applied live: lossRatio=%.3f minStd=%.3f local=%d topK=%d budget=%d lambda=%.2f headroom=%.2f delim=%d",
			live.LossRatio, live.MinBatchStdDev,
			live.LocalContextSize, live.RerankTopK,
			live.ContextBudgetTokens,
			live.DiversityLambda, live.BudgetHeadroomPct, live.PerMsgDelimiterTokens)
	}
	if err := r.cfg.Save(); err != nil {
		return nil, err
	}
	// Hot-reload providers from updated config
	if err := r.substrate.ReloadProviders(ctx); err != nil {
		log.Printf("[Settings] Provider reload: %v", err)
	}
	return r.Query().Settings(ctx)
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*Settings, error) {
	s := r.cfg.Settings
	providers, err := json.Marshal(s.Providers)
	if err != nil {
		return nil, fmt.Errorf("marshal providers: %w", err)
	}
	permissions, err := json.Marshal(s.Permissions)
	if err != nil {
		return nil, fmt.Errorf("marshal permissions: %w", err)
	}
	mcpServers, err := json.Marshal(s.MCPServers)
	if err != nil {
		return nil, fmt.Errorf("marshal mcp servers: %w", err)
	}
	hooks, err := json.Marshal(s.Hooks)
	if err != nil {
		return nil, fmt.Errorf("marshal hooks: %w", err)
	}
	preferences, err := json.Marshal(s.Preferences)
	if err != nil {
		return nil, fmt.Errorf("marshal preferences: %w", err)
	}
	// Serialize engine config from the currently-live engine, not from
	// config file. This lets the UI reflect the actual operating
	// config (including any defaults that kicked in when Settings had
	// zero-value engine fields).
	engine, err := json.Marshal(config.EngineConfigFromRRC(r.substrate.Engine().Config()))
	if err != nil {
		return nil, fmt.Errorf("marshal engine config: %w", err)
	}
	return &Settings{
		Providers:   string(providers),
		Permissions: string(permissions),
		McpServers:  string(mcpServers),
		Hooks:       string(hooks),
		Preferences: string(preferences),
		Engine:      string(engine),
	}, nil
}

// Skills is the resolver for the skills field.
func (r *queryResolver) Skills(ctx context.Context) ([]*SkillInfo, error) {
	loaded := r.Resolver.skills
	result := make([]*SkillInfo, len(loaded))
	for i, s := range loaded {
		result[i] = &SkillInfo{Name: s.Name, Description: s.Description}
	}
	return result, nil
}
